### ISSUE TITLE
problems extending ezSQL_PDO

### ISSUE THREAD

**Issue by surruk51** [ezSQL/ezSQL#102]
Writing a child class of ezSQL_PDO in PHP5 style class syntax, I found that ezSQL(which uses PHP4 class syntax) broke because ezSQL_PDO dynamically creates class properties (they are not declared with the var keyword) in its code. When my class, which had inherited ezSQL tried to refer to these variable, it triggered a __get() method, which of course failed.

In order to fix the problem I had to mod the ezSQL code to declare the following missing variables in ezSQL_PDO class
    var $last_result;
    var $insert_id;

I was surprised to find that ezSQL uses PHP4 style. Are there plans to re-factor, or have I missed something?

**Comment by surruk51** [comment]
Also added 
var $num_rows;

All were added following line 36 in [myplace]
[ez_sql_pdo.php.txt](https://github.com/ezSQL/ezSQL/files/363311/ez_sql_pdo.php.txt)

/ezsql/PDO/ez_sql_pdo.php

**Comment by Scott-Mc** [comment]
Also needs last_query.  Submitted PR for this #117

**Comment by surruk51** [comment]
Do you mean that in PHP4 dialect last_query needs to be declared as a var? I don't think this is necessary as it is declared var in the parent class ezsql_core in my version which is 2.17.

**Comment by Scott-Mc** [comment]
Your right I can see this is declared in ezsql_core.php now,  didn't spot this at first and updated now.

**Comment by surruk51** [comment]
It seems you are re-factoring ezSQL for PHP5/7. When I was using this 
for my project, I considered doing same but did not proceed. However if 
you are working on it and would like some help, I would be happy to join 
in either to do some testing or refactoring.

 From the testing point of view, I have here

PHP Version 7.0.13-0ubuntu0.16.04.1

and

MySQL version  5.7.17-0ubuntu0.16.04.1 Protocol version    10
