### ISSUE TITLE
ezSQL_mysqli::query() handles 'RENAME TABLE' in correctly

### ISSUE THREAD

**Issue by yohancreemers** [ezSQL/ezSQL#108]
The test on line 277 of ez_sql_mysqli.php does not include the 'rename' statement. As a result the script tries to handle the return value of a 'rename table' query as an mysqli_result object.

Suggestion for an improved test: 

``` php
if ( ! preg_match("/^(select|show|describe|explain)/i",$query) )
```

or even less dependent on sql syntax: 

``` php
if ( ! is_object($this->result) )
```

**Comment by ro78** [comment]
I'm not sure it's related, but when I do for example:
```
$mysql->query("RENAME TABLE `routes_new` TO `routes`");
$mysql->query("RENAME TABLE `rcpt_hosts_new` TO `rcpt_hosts`");
```
The second line is not executed.

**Comment by jv2222** [comment]
Is it a time out issue because it's  very large table?

**Comment by yohancreemers** [comment]
The second line should be executed, unless rcpt_hosts already exists or rcpt_hosts_new doesn't exist.
Are you using the the latest version of ezSQL_mysqli?
Does mysql report an error? To find out add `echo $mysql->last_error;` after the last statement.

**Comment by ro78** [comment]
It's a really small table, and $mysql->debug doesn't report any error.
Any command line (like echo) after the first rename line is not executed.

**Comment by jv2222** [comment]
I think that means that it is crashing. Check your php error logs you might
find something useful there.

**Comment by ro78** [comment]
Nothing in PHP logs.
If I use native mysqli php features for these 2 commands, they are successfully executed.
