### ISSUE TITLE
Fatal Error: ezSQL_mysql requires mySQL Lib to be compiled and or linked in to the PHP engine

### ISSUE THREAD

**Issue by sterndata** [ezSQL/ezSQL#111]
Trying to update an old app on Fedora 25.  php-mysqlnd-7.0.13-1.fc25.x86_64 is installed and seems to be working. Am I missing a package or is there an issue with the ezsql library?

**Comment by gnowxilef** [comment]
the only dependency of ezsql is that you have php. if you have package errors, that is most likely on your end.

**Comment by sterndata** [comment]
My error. I needed to change db.inc.php to use **mysqli** instead of mysql.

**Comment by trix1210** [comment]
I have the same error when trying to use it on a localhost with xampp. any solution ? thanks

**Comment by techno-express** [comment]
Well, you not on current ezSQL 3 version, nor PHP 5.6 or greater, nor mysqli. mySQLi is not the same as mySQL, which not supported any longer.
