### ISSUE TITLE
PHP 7 Deprecation error - methods with same name as constructor

### ISSUE THREAD

**Issue by beingmrkenny** [ezSQL/ezSQL#113]
Error message:

PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ezSQL_sqlite3 has a deprecated constructor in [...]/ezsql/ez_sql_sqlite3.inc on line 29

PHP version 7.0.4

**Comment by Scott-Mc** [comment]
I submitted a PR which solves this in #117

**Comment by madvik** [comment]
+1
Same problem

**Comment by jv2222** [comment]
Well I merged @Scott-Mc's work. Let's see what happens! Hopefully the world doesn't fall apart ;)

**Comment by madvik** [comment]
We believe in @Scott-Mc  ;-)

**Comment by Scott-Mc** [comment]
@madvik  I am not sure how wise that is :)  I don't really use this library other than in 1 location but I will keep an eye out for any bugs/submit any PR's if any problems arise,  given what has changed though it should be fine.
