### ISSUE TITLE
Upgrading from V2.03 mysql to latest pdo/msqli

### ISSUE THREAD

**Issue by nirbd** [ezSQL/ezSQL#116]
[ not sure its the right place to ask, if not please refer me] 

I'm using eZsql V2.03 with mysql connector and need to upgrade due to PHP transition from mysql to pdo/mysqli

Is the API 100% compatible for upgrading to the latest  with pdo or mysqli instead of mysql ?
Is there any recommendation for selecting pdo vs myslqi ?

Anything that needs to be changed besides dropping the files?

Thanks,
Nir B

**Comment by yohancreemers** [comment]
ezSQL 2.03 is fully compatible with 2.17. You should have no problems when upgrading.
I've no experience with PDO. Switching from mySQL to mySQLi is painless:

1. Include ez_sql_mysqli.php in stead of ez_sql_mysqli.php
2. Change `$db = new ezSQL_mysql(...)` by `$db = new ezSQL_mysqli(...)`

**Comment by nirbd** [comment]
Thanks a lot Yohan
