### ISSUE TITLE
ezSQL_mysql requires mySQL Lib to be compiled and or linked in to the PHP engine

### ISSUE THREAD

**Issue by OscarWilde** [ezSQL/ezSQL#121]
Since the update of my managed Server, I'm getting this Error.

**ezSQL_mysql requires mySQL Lib to be compiled and or linked in to the PHP engine**

Other Applications not using ezSQL run like normal (e.g. Mantis Bugtracker).

**Comment by jv2222** [comment]
I think you'll need to change to the pdo version or the mysqli version,

**Comment by OscarWilde** [comment]
Yes, thank you! I've changed to mysqli and it worked fine.
