### ISSUE TITLE
PDO paramaters to prevent SQL injection.

### ISSUE THREAD

**Issue by aggarwaldev** [ezSQL/ezSQL#133]
Hey,

I'm using PDO for database interaction and I can't find any example on how to bind parameters to the query in order to prevent SQL injection.

Here's a sample query I'm using:

`$db->get_var("SELECT id FROM users where username = '{$identity}' OR email = '{$identity}' OR mobile = '{$identity}'");`
` return empty($response) ? FALSE : $response;`

It works fine when valid parameters are passed, However when I declare $identity as `' or '1'='1`, It works.

Any way to bind parameters and prevent SQL injection without using html entities or anything?

Thanks,

**Comment by jv2222** [comment]
We had some discussion about adding that to the class, but I don't know if
anyone ever did the work:

https://github.com/ezSQL/ezSQL/issues/68

**Comment by devagg-ar** [comment]
Hey jv2222,

Do you still support the development of ezSQL?

**Comment by jv2222** [comment]
Well not me personally it is now in the hands of the group who manage the
ezSQL team. I do have access to commit though. I would be happy to manage a
team who wanted to modernize ezSQL.

**Comment by devagg-ar** [comment]
@jv2222,

Well, I just hope that the group will update PDO class for ezSQL.

**Comment by techno-express** [comment]
I guess you haven't looked into v3 branch [](https://github.com/ezSQL/ezSQL/tree/v3) all that, and more!
