### ISSUE TITLE
return results in json format

### ISSUE THREAD

**Issue by amanjazari** [ezSQL/ezSQL#137]
Hi,
How to get format output in json when using get_results function ?
Many thanks

**Comment by techno-express** [comment]
change lines that read:
`if ( $output == OBJECT ) {
    return $this->last_result;
} `

to:
`
if ( $output == OBJECT ) {
    return $this->last_result;
} elseif ( $output == 'json' ) { 
    return json_encode($this->last_result); // return as json output
}
`
then call as `get_results($sqlstatement, 'json')`
