### ISSUE TITLE
Warning: Creating default object from empty value in ...

### ISSUE THREAD

**Issue by scottynorris** [ezSQL/ezSQL#140]
I'm getting this error (Warning: Creating default object from empty value in ...) when using get_results. The line it points to is:

$this->col_info[$i]->name =  $meta['name'];

in ez_sql_pdo, which is part of:

for ( $i=0 ; $i < $col_count ; $i++ ) {
                if ( $meta = $sth->getColumnMeta($i) ) {
                    $this->col_info[$i]->name =  $meta['name'];
                    $this->col_info[$i]->type =  $meta['native_type'];
                    $this->col_info[$i]->max_length =  '';
                } else {
                    $this->col_info[$i]->name =  'undefined';
                    $this->col_info[$i]->type =  'undefined';
                    $this->col_info[$i]->max_length = '';
                }
            }

I have error reporting turned on via:

php error_reporting(E_ALL);
ini_set('display_errors', 1);

**Comment by techno-express** [comment]
Can you supply the source routine so i can reproduce, or an test example? 
I don't use PDO in any of my projects, so it will be hard to track down without it.

**Comment by scottynorris** [comment]
I'm literally just setting up ezsql and using get_results in an otherwise blank php file to grab from a very simple 50 row localhost db/table on MAMP:

<?php
require_once ($_SERVER['DOCUMENT_ROOT'] . "/database/config.php");
error_reporting(E_ALL);
ini_set('display_errors', 1);
require_once ($_SERVER['DOCUMENT_ROOT'] . "/database/ezsql/ez_sql_loader.php");

global $db;
$db = new ezSQL_pdo(DB_DSN,DB_USER,DB_PASS);
$userQuery = $db->get_results("SELECT * FROM users");

?>

**Comment by techno-express** [comment]
Which driver you using, PDO mysql, postgres, sqlite...?
There are some phpunit tests for each PDO in tests/pdo/, and general one for mysqli in tests/mysqli/ezSQL_mysqliTest.php that tests get_results, put your code in there, 

Trying input your data in the unit tests.
Or try using `$db->selecting('users', '*');` in your source it ends up calling get_results.

Also are you getting any results or just an error?

**Comment by scottynorris** [comment]
PDO I assume although I'm not 100% on the terminology driver. I'm using pdo based code. I am getting results, the warnings only display if I have errors turned on using:

```
error_reporting(E_ALL);
ini_set('display_errors', 1);
```
So it's only really an issue for testing, but it does seem to point to something going awry. I don't have time for more in-depth testing atm but will endeavour to get round to it.

**Comment by techno-express** [comment]
Thanks for confirming. I'll see what's causing come up with an fix.

**Comment by PSchuetz** [comment]
I've solved this warning notice by initialising  "$this->col_info[$i]" at the begin of the loop at line 371ff:

for ( $i=0 ; $i < $col_count ; $i++ ) {
				// Start DEBUG by psc!
				$this->col_info[$i] = new stdClass();	
				// End DEBUG by psc
               if ( $meta = $sth->getColumnMeta($i) ) {
                    $this->col_info[$i]->name =  $meta['name'];
                    $this->col_info[$i]->type =  $meta['native_type'];
                    $this->col_info[$i]->max_length =  '';
                } else {
                    $this->col_info[$i]->name =  'undefined';
                    $this->col_info[$i]->type =  'undefined';
                    $this->col_info[$i]->max_length = '';
                }
            }

Kind regards, Peter

**Comment by scottynorris** [comment]
This seems to have worked for me - nice job.

**Comment by techno-express** [comment]
@PSchuetz, thanks, haven't had time to further investigate, will implement the fix in new commit.
