### ISSUE TITLE
using ez_sql_pdo: $db->query("INSERT....) does not write entries

### ISSUE THREAD

**Issue by PSchuetz** [ezSQL/ezSQL#141]
Since many years I'm using ezSQL for my projects. 
So i have tons of existing code, all working fine with ez_sql_mysqli.

Now, when I change the config from "ez_sql_mysqli" to "ez_sql_pdo", 
all query() commands using INSERT does not work any more. 

I get a positive result during the execute, everything looks normal in a first view, but the entries are not written to the database.

Do I have to change anything in my code for PDO than if I am using MySQLi?

**Comment by techno-express** [comment]
That's really strange. Take a look at the phpunit tests for mysqli and pdo, add your data, see if not reading the same data back.

**Comment by PSchuetz** [comment]
Yes it is. Everything works fine, except all INSERT commands (giving back an OK, but does not write into the database). Unfortunately, I can't run these tests, since PHPUnit is not installed.

**Comment by techno-express** [comment]
i think it might be your setup. the phpunit tests and results show data is being stored into an actual database and being read back from it. 

Are you using version v3? What pdo driver are you using, sqlite, postgres, mssql, or mysql?

**Comment by PSchuetz** [comment]
I am using the current version of lib/ez_sql_pdo.php. Loaded by ez_sql_loader.php:

$options = array("PDO::ATTR_ERRMODE","PDO::ERRMODE_EXCEPTION");
require_once OLA_SERVER_PFAD."includes/mysql/ez_sql_loader.php"; 
$this->class_db = new ezSQL_pdo("mysql:host=".EZSQL_DB_HOST.";dbname=".EZSQL_DB_NAME,EZSQL_DB_USER,EZSQL_DB_PASSWORD,$options);		

PHPunit is not available on my server, and since it needs some other requires 
(require_once 'PHP/CodeCoverage/Filter.php';) witch is also not installed, I am not really motivated to install it. 

In my opinion, the ez_SQL setup should be OK, since $db->query("DELETE FROM ..."), $db->get_row() and $db->get_results() are working normally.

**Comment by PSchuetz** [comment]
Just found the problem: 
$options = array("PDO::ATTR_ERRMODE","PDO::ERRMODE_EXCEPTION");

was wrong. This must be: 

	$options = array(
            PDO::ATTR_ERRMODE => 'TRUE',
            PDO::ERRMODE_EXCEPTION => 'TRUE'
       );	

With this modification, INSERT query commands are also working fine and I can start using ez_SQL with PDO. Thanks for your support and sorry for my ignorance.

Kind regards, 
Peter
