### ISSUE TITLE
Can you use without composer?

### ISSUE THREAD

**Issue by dpDesignz** [ezSQL/ezSQL#145]
I'm wanting to use this on my sites with the PDO library, however, I can't work out how to actually call it as all the docs I've been finding reference a file called 'ez_sql_core.php' which I can't find?

I'm also wanting to use this without Composer. Is this possible?

Can someone please advise what files I need to have on my server to use the PDO library and how to call it without composer?

**Comment by techno-express** [comment]
The docs needs updating they reference version 2.1.7, the current supported version is **3.0.8**.
>The README.md file has an how to use without composer, which is:

**`require_once "ez_sql_loader.php";`**

**Comment by dpDesignz** [comment]
Ah thanks, I was confused by the spl_autoload_register() function. Looking forward to using this. Any ideas when the docs will be updated to reflect the new stuff?

**Comment by techno-express** [comment]
Take at look at the phpunit tests, https://github.com/ezSQL/ezSQL/tree/master/tests/pdo
