### ISSUE TITLE
PDO Examples

### ISSUE THREAD

**Issue by dpDesignz** [ezSQL/ezSQL#146]
Would someone be willing to post or point me in the direction of finding some examples of the PDO version being used? I'm wanting to build some queries but as the documentation is now out of date it's not working.

**Comment by techno-express** [comment]
You need to take a look at the PDO phpunit tests https://github.com/ezSQL/ezSQL/tree/master/tests/pdo

There is no PDO version to reference. What PHP version you using? 
It seems you need general help with SQL and PHP. The library just simplify or help with the **D.R.Y.** principle, Don't Repeat Yourself.

**Comment by dpDesignz** [comment]
I had a look at the test file a few days ago, but it had functions in there that aren't documented and I didn't know how they worked. Apologies, I should have clicked that it's universal functions, I've just seen comments about prepared statements for the PDO extension and assumed that it was exclusive to that. I'm using PHP7. 

I'm fine with SQL and PHP, I just couldn't seem to get the "WHERE" array to accept more than 1 value. So for example if I did `WHERE fieldname = test` it would work, but if I also added a second item to the array that was ` AND fieldname = dummy` it didn't seem to execute that second part.
The other part was a SELECT statement using the $args I couldn't get it to work.

I can post what I have so far for examples if that would help? Sorry I'm not at my computer currently so will post later today.

**Comment by techno-express** [comment]
Posting the code example of what you are doing would help.

**Comment by dpDesignz** [comment]
Now that I understand that `assertEquals` and `assertTrue` are PHPUnit functions, I finally see how the queries are built.

I understand how the `this->escape("This isn't escaped.")` works, but I also see a function in the `ez_sql_pdo.php` file on line `261` called `query_prepared` which I don't entirely understand. And in turn, on line `279` called `query`.

So this is a simple code I wrote to insert a line and then update it:

`$insertID = $csdb->insert('dummy_data',array('dummy_data'=>'test','dummy_data2'=>'test2'));
$csdb->debug();
$dataArray['dummy_data'] = 'testchanged';
$whereOne = 'dummy_id = ' . $insertID . ' and';
$whereTwo = 'dummy_data2 = test2';
$csdb->update('dummy_data', $dataArray, $whereOne, $whereTwo);
$csdb->debug();
exit();`

However, both debugs are giving me

>  Query [1] -- [INSERT INTO dummy_data(dummy_data, dummy_data2) VALUES ('test', 'test2');]
Query Result..
    No Results

so I'm not getting the `UPDATE` as the second one.

**Comment by techno-express** [comment]
**Your code formatted:**
```php
$insertID = $csdb->insert('dummy_data', 
	array('dummy_data1'=> 'test', 'dummy_data2'=>'test2'));

$csdb->debug(); 

$dataArray['dummy_data1'] = 'testchanged'; 

$whereOne = 'dummy_id = ' . $insertID . ' and';

$whereTwo = 'dummy_data2 = test2'; 

$csdb->update('dummy_data', $dataArray, $whereOne, $whereTwo); 

$csdb->debug();

$result = $csdb->selecting('dummy_data', 'dummy_data1', eq('dummy_data2', 'test2'), eq('dummy_id',$insertID));

foreach ($result as $row) { 
	echo $row->dummy_data1; 
} 

$csdb->debug(); 
exit();
```
**This line**
> $result = $csdb->selecting('dummy_data', 'dummy_data1', eq('dummy_data2', 'test2'), eq('dummy_id',$insertID));

**Should read**
>$result = $csdb->selecting('dummy_data', 'dummy_data1', $csdb->where($whereOne, $whereTwo));

**Or**
>$result = $csdb->selecting('dummy_data', 'dummy_data1', eq('dummy_data2', 'test2', _AND), eq('dummy_id',$insertID));

The example you posted is not correct. Take another look at the phpunit tests, fill your info into. Look at https://github.com/ezSQL/ezSQL/blob/master/tests/mysqli/ezSQL_mysqliTest.php and https://github.com/ezSQL/ezSQL/blob/master/tests/postgresql/ezSQL_postgresqlTest.php

All the method shortcuts calls `insert`, `update`, `selecting`, `delete`, work the same regarding of database vendor. They reduce parameters/arguments to proper SQL statements.

There are various ways to do where clause, just stay consistent.
There are more shortcuts calls like `LIMIT` in my **Todo**.

**Comment by dpDesignz** [comment]
Ah thanks, when I posted my code it was formatted in the editor, but I couldn't work out how to format it once it was posted. :)

So my select is actually working no problems and when I check the debug it's returning `SELECT dummy_data1 FROM dummy_data WHERE dummy_data2 = 'test2' AND dummy_id = '24'`, so that's fine (but thanks for the alternatives for the `WHERE`, I'm just having a play with them now).

Can you please confirm what the difference is between the `selecting` function and the `get_` functions that are referenced in the current docs? Say for example I want to use the `$db->get_row`, from what I understand looking at the examples and docs, I need to write out the full query, is that correct?

Where I'm actually having issues with my example code is this line:

> `$csdb->update('dummy_data', $dataArray, $whereOne, $whereTwo);`

Which I managed to get to work by changing it to

> `$csdb->update('dummy_data', $dataArray, eq('dummy_id',$insertID, _AND), eq('dummy_data2','test2'));`

However I want to be dynamically adding to the `WHERE` clause in most situations, which is why I tried some array options, but they never worked. How would I write my code so I can build an array of `WHERE` options? Is this possible, or am I trying to push it a bit too far? I'm wanting this for any query (`insert`, `update`, `selecting`, `delete`).

So for example, building a "Search & Filter" system, I check if, say, an html `select` has a value, and if it does, it adds it to the `WHERE` array. Is this possible, or should I just build my string dynamically and add that as the `$where` key?

Thanks for clarifying about `LIMIT`. I might try add it in my end for now in the `selecting` function.

**Comment by techno-express** [comment]
Using the `get_` functions directly require full SQL statements.

Dynamically adding to the `WHERE` clause is possible, which is general PHP setup code. What have you tried that is not working? What you posted as not working is not in array layout.

Also take an look at the **`WHERE`** and **`SELECTING`** methods comment/doc-block https://github.com/ezSQL/ezSQL/blob/master/shared/ezQuery.php
While going over it now, I realize, they too needs updating, and reformat styling, another **Todo**.

**Comment by dpDesignz** [comment]
Cool, thanks for clarifying about the `get_` functions. :)

So for example I tried the following:

> $insertID = '24';
$dataArray['dummy_data1'] = 'newData';
$whereArray = array();
$whereArray[] = 'dummy_id = ' . $insertID . ' and';
$whereArray[] = 'dummy_data2 = test2';
$csdb->update('dummy_data', $dataArray, $whereArray);
$csdb->debug();

however it does absolutelty nothing. I don't even get an error log.

Thanks for those references. I've been pouring over that file in depth as much as possible the last couple of days. I've got my head wrapped around most of it I think.

**Comment by techno-express** [comment]
have an check like `if ($csdb->update('dummy_data', $dataArray, $whereArray) === false)` which will be true, cause the string is not double spaced for separation of items.  The actually where cause needs each item to be array, or an string with each item double spaced of item.  

Your example is single spaced. The `where` method clause method states items either an _array_ or _double spaced_ for separation.
> $whereArray[] = 'dummy_data2 = test2';

**to**
>$whereArray = ['dummy_data2', '=', 'test2'];

**or**
>$whereArray = eq('dummy_data2', 'test2'); // eq(column/constant/key, $value);

**or**
>$whereArray = 'dummy_data2  =  test2'; // items double spaced

The functions in https://github.com/ezSQL/ezSQL/blob/master/shared/ezFunctions.php should be used instead with the **where** clause. It reduces all the unnecessary writing.

**Comment by dpDesignz** [comment]
> 
> 
> have an check like `if ($csdb->update('dummy_data', $dataArray, $whereArray) === false)` which will be true, cause the string is not double spaced for separation of items. The actually where cause needs each item to be array, or an string with each item double spaced of item.
> 
> Your example is single spaced. The `where` method clause method states items either an _array_ or _double spaced_ for separation.
> 
> > $whereArray[] = 'dummy_data2 = test2';
> 
> **to**
> 
> > $whereArray = ['dummy_data2', '=', 'test2'];
> 
> **or**
> 
> > $whereArray = eq('dummy_data2', 'test2'); // eq(column/constant/key, $value);
> 
> **or**
> 
> > $whereArray = 'dummy_data2  =  test2'; // items double spaced
> 
> The functions in https://github.com/ezSQL/ezSQL/blob/master/shared/ezFunctions.php should be used instead with the **where** clause. It reduces all the unnecessary writing.

Thanks, that actually makes so much sense! My only issue with this is this is for only 1 where clause, and I'm wanting to add multiple clauses. So my example I've posted above should end up like this:

> WHERE `dummy_id` = '24' AND `dummy_data2` = 'test2'

So my line

> $csdb->update('dummy_data', $dataArray, $where);

would be having the `$where` as a finished full `WHERE` statement somehow. This is where I'm getting myself confused.

I'm trying to dynamically add to the `$where` key. Sometimes I'll only want it to be by one value, but most of the time it will need to be by multiple values. I'm super keen to use the functions in the **ezFunctions** file, I am just trying to work out how to use multiples of them in 1 where key, or however it needs to be done. I'm only assuming this can be done? I tried using the if check you just showed and it keeps coming back true if I try to have multiple `WHERE` clauses in there.

I also just tried the following, but of course it didn't work :(

> $whereArray = array();
$whereArray[] = eq('dummy_id', '24', _AND);
$whereArray[] = eq('dummy_data2', 'test2');
$csdb->update('dummy_data', array('dummy_data1'=>'newData'), $csdb->where($whereArray));
$csdb->debug();

Thank you so much for taking the time to try help me by the way.

**Comment by techno-express** [comment]
What you are trying is already part of the where clause. 
The is no need for creating array like you have `$whereArray = array();`
And:
>$whereArray[] = eq('dummy_id', '24', _AND);
>$whereArray[] = eq('dummy_data2', 'test2');

Could Try:
>$whereArray = [eq('dummy_id', '24', _AND), eq('dummy_data2', 'test2')]; // not sure about

Or better:
>$csdb->update('dummy_data', ['dummy_data1'=>'newData'], $csdb->where(eq('dummy_id', 24, _AND), eq('dummy_data2', 'test2')));

Anyway, the where clause is variadic function. I accepts any number of arguments. The way you are passing them in is the problem. The arguments are either string or array, and detected and parsed as such. You passing an array in a array, and will not be detected as arguments.

**Comment by dpDesignz** [comment]
> 
> 
> What you are trying is already part of the where clause.
> The is no need for creating array like you have `$whereArray = array();`
> And:
> 
> > $whereArray[] = eq('dummy_id', '24', _AND);
> > $whereArray[] = eq('dummy_data2', 'test2');
> 
> Could Try:
> 
> > $whereArray = [eq('dummy_id', '24', _AND), eq('dummy_data2', 'test2')]; // not sure about
> 
> Or better:
> 
> > $csdb->update('dummy_data', ['dummy_data1'=>'newData'], $csdb->where(eq('dummy_id', 24, _AND), eq('dummy_data2', 'test2')));
> 
> Anyway, the where clause is variadic function. I accepts any number of arguments. The way you are passing them in is the problem. The arguments are either string or array, and detected and parsed as such. You passing an array in a array, and will not be detected as arguments.

Ok I tried your bottom example and it's still not working. The debug is returning a select from earlier on in my documentation which is obviously the last operation to execute. :(

This is what I tried

>$csdb->update('dummy_data', ['dummy_data1'=>'newData'], $csdb->where(eq('dummy_id', '24', _AND), eq('dummy_data2', 'test2')));
$csdb->debug();

I added an echo at line 456 of the `ezQuery` file to see what it was outputting and it returned

> UPDATE dummy_data SET dummy_data1 = 'newData', 

So for some reason line 448 is not triggering the `$where = $this->where(...$wherekeys);`, or at least returning a result.

At line 448 I tried

>$where = $this->where(...$wherekeys);
print_r(...$wherekeys);
exit();

which output my `WHERE` clause as a complete string, but if I put 

>$where = $this->where(...$wherekeys);
print_r($where);
exit();

it returned blank. So I changed line 448 to

>if (!is_string( ...$wherekeys )) {
    $where = $this->where(...$wherekeys);
} else {
    $where = $wherekeys[0];
}

and it worked, but obviously I don't want to have to change this core code to make it work as next time I update ezSQL it will break :(

This also still doesn't solve my issue as in this example I know exactly what is in the `WHERE` clause, but how would I build my clause if I'm basing it off user input variables?

So for example I might have code like this.

>$whereArray[] = (isset($_GET['dummy_data2'])) ? eq('dummy_data2',$_GET['dummy_data2'],_AND) : '';
$whereArray[] = (isset($_GET['dummy_id'])) ? eq('dummy_id',$_GET['dummy_id'],_AND) : '';
$result = $csdb->selecting('dummy_data', 'dummy_data1', $csdb->where($whereArray));
foreach($result  as $row ) {
	echo ( empty( trim( $row->dummy_data1 ) ) ) ? $default : $row->dummy_data1;
}
$csdb->debug();
exit();

Which of course gives the error `Warning: strtoupper() expects parameter 1 to be string, array given...` as you mentoned before as it's an array in an array, however if I tried the following code

>$whereArray = (isset($_GET['dummy_data2'])) ? eq('dummy_data2',$_GET['dummy_data2'],_AND) : '';
$whereArray = (isset($_GET['dummy_id'])) ? array_merge($whereArray, eq('dummy_id',$_GET['dummy_id'],_AND)) : '';
$result = $csdb->selecting('dummy_data', 'dummy_data1', $csdb->where($whereArray));
foreach($result  as $row ) {
	echo ( empty( trim( $row->dummy_data1 ) ) ) ? $default : $row->dummy_data1;
}
$csdb->debug();
exit();

Which makes it one big array and returns it as `Array ( [0] => dummy_data2 [1] => = [2] => test2 [3] => AND [4] => dummy_id [5] => = [6] => 24 [7] => AND )` the code now executes, but the debug returns

>Query [1] -- [SELECT dummy_data1 FROM dummy_data WHERE dummy_data2 = 'test2']

Which shows that it's only seeing the first `WHERE` clause in the array? Interestingly if I changed `$csdb->where($whereArray)` to just `$whereArray` it gives the same result

> $whereArray = (isset($_GET['dummy_data2'])) ? eq('dummy_data2',$_GET['dummy_data2'],_AND) : '';
$whereArray = (isset($_GET['dummy_id'])) ? array_merge($whereArray, eq('dummy_id',$_GET['dummy_id'],_AND)) : '';
$result = $csdb->selecting('dummy_data', 'dummy_data1', $whereArray);
foreach($result  as $row ) {
	echo ( empty( trim( $row->dummy_data1 ) ) ) ? $default : $row->dummy_data1;
}
$csdb->debug();
exit();

>Query [1] -- [SELECT dummy_data1 FROM dummy_data WHERE dummy_data2 = 'test2']

**Comment by techno-express** [comment]
>$whereArray = (isset($_GET['dummy_id'])) ? array_merge($whereArray, eq('dummy_id',$_GET['dummy_id'],_AND)) : '';

You aren't passing in parameters to the function. **`where(...$args)`** translates to **`where($args[0], $args[1], $args[2], and so on...)`** and that's done by PHP itself, not the **where** function. 

You are actually passing in **`where($args[0])`** only! And Line 448:
>$where = $this->where(...$wherekeys);

Should return blank because it is returning false for error.
>$csdb->update('dummy_data', ['dummy_data1'=>'newData'], $csdb->where(eq('dummy_id', '24', _AND), eq('dummy_data2', 'test2')));
$csdb->debug();

Well there might be an issue with the where function itself, but the tests currently passing shows otherwise. And they are using multiple where clauses. So setup the phpunit tests locally, plug your data in for test data.

**Comment by dpDesignz** [comment]
Sadly although I've been coding PHP for almost 10 years now, I have been away from it for over a year and I'm only just getting back into it, so sorry for the back and forth.

In that, I've just installed composer and run the install command in the ezSQL-master folder, where it installed phpunit v8.0.4 and all the other dependencies referenced in the composer.json file, however when I try to run the script with `composer run-script test` it returns the following

> phpunit --bootstrap vendor/autoload.php tests
PHPUnit 8.0.4 by Sebastian Bergmann and contributors.
Cannot open file "vendor/autoload.php".
Script phpunit --bootstrap vendor/autoload.php tests handling the test event returned with error code 1

As I've never used composer before (I only started using npm last year) I'm not sure what to do to troubleshoot this. I've done some googling, but that didn't really help unfortunately. :(
If you wouldn't mind, what do I need to do to get the test executing?

I've been looking at the `ezSQL-master\tests\pdo\ezSQL_pdo_mysqlTest.php` file again, as since I'm using the `ezSQL-master\lib\ez_sql_pdo.php` file, I'm assuming this would be the file I'm trying to emulate. So the test lines for `update` for example are lines 193-197, and `selecting` are line 238-260. None of these show a way to have multiple clauses in them without knowing what they are at execute.

So for example line 194 (`$this->assertEquals($this->object->update('unit_test', $unit_test, eq('test_key','test 3', _AND), eq('id','3')), 1);`) shows 2 clauses, but they are known and in the function itself.
Same again in line 196 (`$this->assertEquals($this->object->update('unit_test', $unit_test, "test_key  =  test 2  and", "id  =  2"), 1);`) there are 2 there, as strings, double spaced, but again, they are in the function itself, not created dynamically and added in.


**##### UPDATE #####**

I worked it out!!! Duh, it was so obvious!

>$whereArray[] = eq('dummy_data2', 'test2', _AND);
$whereArray[] = eq('dummy_id', '24', _AND);
$whereArray[] = like('dummy_data1', 'new%', _AND);
$result = $csdb->selecting('dummy_data', 'dummy_data1', ...$whereArray);
foreach($result as $row ) {
echo ( empty( trim( $row->dummy_data1 ) ) ) ? $default : $row->dummy_data1;
}
$csdb->debug();
exit();

Gives me

>SELECT dummy_data1 FROM dummy_data WHERE dummy_data2 = 'test2' AND dummy_id = '24' AND dummy_data1 LIKE 'new%'

and

> $whereArray[] = eq('dummy_id', '24', _AND);
$whereArray[] = like('dummy_data1', 'new%', _AND);
$csdb->update('dummy_data', array('dummy_data2'=>'itWorked!'), ...$whereArray);

Gives me

>UPDATE dummy_data SET dummy_data2 = 'itWorked!' WHERE dummy_id = '24' AND dummy_data1 LIKE 'new%'

Thank you so much for all your help! :D

**Comment by techno-express** [comment]
That's good! 

I realize from my last reply, and looking at the **where** and **update** method again. It wasn't detecting string, and if the string already has the **WHERE** statement within it, it should skip, return as is. 
So:
> $csdb->update('dummy_data', ['dummy_data1'=>'newData'], $csdb->where(eq('dummy_id', '24', _AND), eq('dummy_data2', 'test2')));
> $csdb->debug();

I mean the `$csdb->where(...);` within `$csdb->update()`, which i shouldn't written and gave you, you actually discovered the problem and is like writing instead:
> $csdb->update('dummy_data', ['dummy_data1'=>'newData'], eq('dummy_id', '24', _AND), eq('dummy_data2', 'test2'));
> $csdb->debug();

The `where(...$args)` in general is returning an SQL string, not detecting results of if the `where(...$args)` clause itself is being passed in also. Which is what i gave you to do. 

I will be doing an commit today to address the issue.

**Comment by dpDesignz** [comment]
Ah sweet. So do I still need to put it in a `where()` function with this new commit, or keep it how I've got it just fine? Thanks again for all your help :)

**Comment by techno-express** [comment]
It doesn't matter. Maybe for your code readability at some later time. But
you have it structured correctly from what I see, and might be unessary
additional processing.
