### ISSUE TITLE
Encrypted connections with ssl in mysql

### ISSUE THREAD

**Issue by peopleplaces** [ezSQL/ezSQL#148]
Looks like we can use SSL with PDO. Is there plans or a means of securing connections using mysqli ?

**Comment by techno-express** [comment]
I did an quick search, doesn't seem like it would be to hard to integrate
into. However, it might just be specific to mysqli, not any of the other
SQL drivers.

I will add the feature to the projects Todo's for all SQL drivers.

**Comment by techno-express** [comment]
Yes, I will be working the feature in, the option is available in the other PDO SQL drivers.

**Comment by techno-express** [comment]
Has been incorporated in latest/commit release https://github.com/ezSQL/ezSQL/commit/b9dcfe5b5256913843cb533a04f19e68d87d8e77
