### ISSUE TITLE
Possible error in ez_sql_sqlsrv.php

### ISSUE THREAD

**Issue by curmudgeon61** [ezSQL/ezSQL#149]
To use this lib, I needed to change line 162 from:
if($this->convertMySqlTosqlsrvQuery == true)
To:
if($this->convertMySqlToMSSqlQuery == true)

$this->convertMySqlTosqlsrvQuery does not exist anywhere else in the file except line 162

**Comment by techno-express** [comment]
I can confirm the error, need an phpunit test to cover the conversion feature, or why the tests not catching it.

I will commit an bug fix release covering the issue by the end of the day.

**Comment by techno-express** [comment]
Has been incorporated in latest/commit release https://github.com/ezSQL/ezSQL/commit/b9dcfe5b5256913843cb533a04f19e68d87d8e77
