### ISSUE TITLE
Error with some parameters that are now protected

### ISSUE THREAD

**Issue by holyguard** [ezSQL/ezSQL#150]
Hello, i have just updated the old EzSql library

some parameters are now protected and i cannot access to them from outside the class

`
$db->cache_timeout = 240;
$db->cache_dir = $_SERVER['DOCUMENT_ROOT'] . '/cache/ezsql/';
$db->use_disk_cache = false;
$db->cache_queries = false;
`
i get this error:
`Uncaught Error: Cannot access protected property ezSQL_pdo::$cache_timeout in...`
how can i solve this?

Thanks,

**Comment by techno-express** [comment]
The library is in an slow process of getting moved over to be more OOP's and PSR compliant. I did an change and ran the phpunit tests, the ones that gave errors was keep public for now. But all will be eventually changed to protected. I guess there wasn't an test already covering that property to catch. 

You could change it back to public in `ez_sql_core.php`.
Or, you can add this to `ez_sql_core.php`:
```
	/**
	* Use for Calling Non-Existent Functions, handling Getters and Setters
	* @param function set/get{name} = private/protected property that needs to be accessed
	*/
	public function __call($function, $args) 
	{
		$prefix = substr($function, 0, 3);
		$property = strtolower(substr($function, 3, strlen($function)));
		if ($prefix == 'set') {
			$this->$property = $args[0];
		} elseif ($prefix == 'get') {
			return $this->$property;
		} else {
			throw new \Exception("$function does not exist");
		}
	}
```
Then test access by `$db->setCache_Timeout(240);` or `$db->getCache_Timeout();`

The above code with be committed by the end of today.
