### ISSUE TITLE
Initializing db error

### ISSUE THREAD

**Issue by usabilitest** [ezSQL/ezsql#152]
I've re-installed composer and ezsql (v3). I've verified that both files exist relative to my test file (/public_html/test.php), but I'm still not able to initialize the db. I've tried the  following approaches:

```
require_once '../vendor/ezsql/ezsql/ez_sql_loader.php';
$setting = new Config('mysqli', ['my_usr', 'my_pass', 'my_db', 'localhost']);
$db = new ez_mysqli($settings);
```
then I tried:
```
require_once '../../../vendor/autoload.php';
$db = Database::initialize('mysqli', ['my_usr', 'my_pass', 'my_db', 'localhost']);
```
unfortunately in both cases I got the following error:

> received error: Fatal error: Default value for parameters with a class type hint can only be NULL in /home/mydomain/vendor/ezsql/ezsql/shared/ezFunctions.php on line 247

What am I missing?

**Comment by techno-express** [comment]
read https://github.com/ezSQL/ezsql/blob/v3/README.md and database setup is the same as v2

Version 4 is an whole different approach, which you can't use, as you are trying to do.

**Comment by usabilitest** [comment]
OK, I was able to get my old ezsql v2.03 to work by doing the following:

```
include_once '../include/lib/ezsql/shared/ez_sql_core.php';
include_once '../include/lib/ezsql/mysql/ez_sql_mysql.php';
include_once '../include/lib/ezsql/db_connect.inc.php'; 
```
The problem is that it only works under PHP 5.6 and breaks under v7.

If I were to change to newly installed v3 what would my PHP code look like? I'm so confused at this point that it's not even funny. The above reference to README file, provides absolutely no insight into how to get v3 going - it's basically a changelog. I'd I appreciate any help I can get at this point.

**Comment by techno-express** [comment]
It's require 'ez_sql_loader.php', if not using composer. As readme show.
Take an look at the phpunit tests folder in v3 branch. it shows full
database setup and tests that are real database tests, no mocks.

If there where any real issue then the status badges would show so as
failing.

**Comment by usabilitest** [comment]
I've added the following:
`require_once '../vendor/ezsql/ezsql/ez_sql_loader.php';`
So far so good. However, when I add the following:
```
$setting = new Config('mysqli', ['my_usr', 'my_pass', 'my_db', 'localhost']);
$db = new ez_mysqli($settings);
```
I get the following PHP error:

> Fatal error: Uncaught Error: Class 'Config' not found in /home/bahai/public_html/test.php:31 Stack trace: #0 {main} thrown in /home/bahai/public_html/test.php on line 31

Line 31 is: $setting = new Config('mysqli', ['my_usr', 'my_pass', 'my_db', 'localhost']);

I looked at the phpunit tests but I don't really understand what I'm suppose to see there. Do I need to copy these tests to public_html directory in order to run? I need to initialize $db in order for my code to work and I can't seem to be able to figure it out. I came a cross a few other requests for demo page from similarly lost folks.  I think having an example code, like the original ezsql had would be very beneficial.

**Comment by techno-express** [comment]
I keep writing one thing and you another 
>require_once '../vendor/ezsql/ezsql/ez_sql_loader.php';

is WRONG! that is not how composer is used. `require 'vendor/autoload.php'` nothing else.

If not using composer, it just loading 'ez_sql_loader.php' file and nothing else, not from the vendor location. delete that folder if not using composer. you are confusing yourself.

> $setting = new Config('mysqli', ['my_usr', 'my_pass', 'my_db', 'localhost']);
$db = new ez_mysqli($settings);

That is only for version 4.

Why not `new ezSQL_mysqli('db_user','db_password','db_name','db_host');` like v2.
example demo for v2 is https://github.com/ezSQL/ezsql/blob/v2/mysqli/demo.php

The v3 mysqli examples see tests https://github.com/ezSQL/ezsql/blob/v3/tests/mysqli/ezSQL_mysqliTest.php

**Comment by usabilitest** [comment]
Thanks for clarification. I downloaded the ZIP file from here: https://github.com/ezSQL/ezsql/tree/v3, unzipped and this time FTP all files to /public_html/incl/lib/ezsql

Then I added to the following to my test.php file, following v2 format:
```
include_once 'incl/lib/ezsql/shared/ez_sql_core.php';
include_once 'incl/lib/ezsql/lib/ez_sql_mysqli.php';
$db = new ezSQL_mysqli('my_usr', 'my_pass', 'my_db', 'localhost'); 
```
Now I'm getting a different error:

> Fatal error: Interface 'ezsql\ezQueryInterface' not found in /home/mydomain/public_html/incl/lib/ezsql/shared/ezQuery.php on line 6

I still don't get what am I supposed to see in test file... It's 554 lines of functions code. The hope starts to fade away...

**Comment by techno-express** [comment]
why?
>include_once 'incl/lib/ezsql/shared/ez_sql_core.php';
include_once 'incl/lib/ezsql/lib/ez_sql_mysqli.php';

Version 3, Just
`require_once "ez_sql_loader.php";` 

 Which is stated in the change log, and readme. What you are doing now, is for version v2, at https://github.com/ezSQL/ezsql/tree/v2

PHP is now at 7.3.4, autoloading classes is the way things are going. You are getting the error you should get.

**Comment by usabilitest** [comment]
So sorry, that's what I understood when you gave v2 example... my bad. 

Anyhow, it finally worked. I volunteer to contribute a demo code snippet for those in my situation, if needed.

What I can do now is:

1. Transition ezSQL to v.3
2.  Upgrade PHP to 7+ on the entire server, and not just /public_html without breaking live site
3. Install composer and ezSQL v.4

Thanks for sticking with me through this confusion.

BTW, is v.3 stable all the way through PHP 7.3.4?

Cheers

**Comment by techno-express** [comment]
yes, but version 4 is close to an redesign, different programming principles, moving towards more OOP, and PSR standards.

**Comment by usabilitest** [comment]
Great. That's in my step #3.
