### ISSUE TITLE
selecting() not get correct columns in results

### ISSUE THREAD

**Issue by t-walker-wei** [ezSQL/ezsql#153]
**Describe the bug**
selecting() not get correct columns in results.I query multiple columns,but alway only get the last one in the result.

**Environment (please complete the following information):**
 - EZSQL Version : 4.0.0
 - PHP Version: 7.1.2
 - SQL Driver:mysql

**PHP code snippet used**

```php
require 'vendor/autoload.php';

use ezsql\Config;
use ezsql\Database\ez_mysqli;
$settings = new Config('mysqli',['root','root','k99_iot_monitor','localhost']);
$db = new ez_mysqli($settings);
$db->prepareOn();
$result = $db -> selecting( 'users', 'tel_num, email', $db -> where(eq( 'user_name', 'walker' )) );
$db->debug();
print_r( $result );

```

**This is what I got.**

ezSQL (v4.0.0) Debug..
Query [1] -- [SELECT tel_num, email FROM users WHERE user_name = ?]

Query Result..

(row)	

1	walker@mail.com
Array ( [0] => stdClass Object ( [email] => walker@mail.com ) )

**Comment by techno-express** [comment]
I can confirm the bug, turning off prepare usage `$db->prepareOff();` with shortcut methods get correct column results. 

Will be working on fix and submitting new commit/release by end of day.

**Comment by techno-express** [comment]
I have address this issue with an phpunit test base off your code snippet.
https://github.com/ezSQL/ezsql/blob/065832884fe2fb7c9513af58986c1eaae80be6a6/tests/mysqli/mysqliTest.php#L425

Try the new release do `composer update` first.

**Comment by t-walker-wei** [comment]
I got warning after update.
`Warning: Parameter 1 to mysqli_stmt::bind_result() expected to be a reference, value given in D:\xampp-portable-win32-7.1.2-0-VC14\htdocs\dashboard-template\vendor\ezsql\ezsql\lib\Database\ez_mysqli.php on line 220`
And the result is empty.But if I don't use the where condition, I can get the right columns.

**Comment by techno-express** [comment]
>And the result is empty.But if I don't use the where condition, I can get
the right columns.

What is the actual new code snippet you used? The tests link above posted
not giving warning and have the right  column results, and using where
condition.

**Comment by techno-express** [comment]
There is an issue in `fetch_prepared_result` private method in the storing results into `col_info` property, that the `debug` method call is using to display. 

Still working on another bug fix and will be reverting parts of the last commit. and this new commit will pass the tests because `last_result` property is actually used in all the query method calls. 

The problem is in lines 216 to 233. the `col_info` not right, but `last_result` are right. Until an real fix is submitted the `debug` call when using `prepareOn` not reliability.

**Comment by t-walker-wei** [comment]
It works now.

**Comment by techno-express** [comment]
No, just updated to be off, it shouldn't been on by default, you will need to do `setDebug_Echo_Is_On(true); ` to set enable.

Also, just did another new release updated to v4.0.4, i had to refactor all ezSQL drivers, various other issues was present in all `query_prepared` when called directly.
