### ISSUE TITLE
 Creating default object from empty value in ...\ezsql\ezsql\lib\Database\ez_pgsql.php on line 206

### ISSUE THREAD

**Issue by hubaishan** [ezSQL/ezsql#155]
**Describe the bug**
A warning massage 
` Warning: Creating default object from empty value in ...\ezsql\ezsql\lib\Database\ez_pgsql.php on line 206`

**Expected behavior**
maybe 4 times before every query

**Environment (please complete the following information):**
 - EZSQL Version : 4.0.4 
 - PHP Version: 7.2
 - SQL Driver:pgsql

**Comment by techno-express** [comment]
You are missing the required code snippet.

**Comment by techno-express** [comment]
I'm closing this for now, reopen with necessary info.

**Comment by hubaishan** [comment]
open please.

**Comment by techno-express** [comment]
What is your environment like setting? The passing tests for that is in https://github.com/ezSQL/ezsql/blob/bf5f130979bc859933f330fc0132017e6c4476f3/tests/postgresql/postgresqlTest.php#L253

It's not displaying any warning. `selecting()` actually calls `$db->get_results()`

You will need to give full example or run the tests with your data.

**Comment by hubaishan** [comment]
How to run tests?

**Comment by techno-express** [comment]
Linux: `vendor/bin/phpunit`

Windows: `vendor\bin\phpunit`

**Comment by hubaishan** [comment]
`PHPUnit 8.1.6 by Sebastian Bergmann and contributors.

..............EE..                                                18 / 18 (100%)

Time: 841 ms, Memory: 4.00 MB

There were 2 errors:

1) ezsql\Tests\postgresql\postgresqlTest::testSelecting
Creating default object from empty value

D:\web_server\www\ezsql-4.0.4\lib\Database\ez_pgsql.php:206
D:\web_server\www\ezsql-4.0.4\lib\Database\ez_pgsql.php:299
D:\web_server\www\ezsql-4.0.4\lib\ezsqlModel.php:330
D:\web_server\www\ezsql-4.0.4\lib\ezQuery.php:514
D:\web_server\www\ezsql-4.0.4\tests\postgresql\postgresqlTest.php:264

2) ezsql\Tests\postgresql\postgresqlTest::testQuery_prepared
Creating default object from empty value

D:\web_server\www\ezsql-4.0.4\lib\Database\ez_pgsql.php:206
D:\web_server\www\ezsql-4.0.4\lib\Database\ez_pgsql.php:146
D:\web_server\www\ezsql-4.0.4\tests\postgresql\postgresqlTest.php:315

ERRORS!
Tests: 18, Assertions: 40, Errors: 2.`

**Comment by hubaishan** [comment]
i fix the bug by adding 
`
                    $this->col_info[$i] = new \stdClass();
`
before https://github.com/ezSQL/ezsql/blob/bf5f130979bc859933f330fc0132017e6c4476f3/lib/Database/ez_pgsql.php#L207

**Comment by techno-express** [comment]
Good catch! Summit the change and test with an PR.

**Comment by techno-express** [comment]
Stilling waiting on your PR, and now notice you still haven't given the anything you are referencing, **no actually code!** If there are any real **errors/bugs** i would see them already in the ci build. You must have issues in your code.
