### ISSUE TITLE
How To Initialize DB?

### ISSUE THREAD

**Issue by parkerj** [ezSQL/ezsql#156]
**Installed via:** composer
**Version:** dev-master
**PHP Version:** PHP 7.2.1
**IDE**: Netbeans 9

Here is some code from my class:

```php
use ezsql\Database;

*******************

    public function __construct(array $config = [])
    {
        $this->config = $config;
    }
    
    public function setUp()
    {        
        $this->config['driver'] = ($this->config['driver'] ? $this->config['driver'] : 'mysql');
        $this->config['charset'] = ($this->config['charset'] ? $this->config['charset'] : 'utf8mb4');
        $this->config['collation'] = ($this->config['collation'] ? $this->config['collation'] : 'utf8mb4_unicode_ci');
        $this->config['host'] = ($this->config['host'] ? $this->config['host'] : '127.0.0.1');
        $this->config['port'] = (strstr($this->config['host'], ':') ? explode(':', $this->config['host'])[1] : '');

        $this->dsn = '';

        if ($this->config['driver'] == 'mysql' || $this->config['driver'] == '' || $this->config['driver'] == 'pgsql') {
            $this->dsn = $this->config['driver'] . ':host=' . $this->config['host'] . ';'
                . (($this->config['port']) != '' ? 'port=' . $this->config['port'] . ';' : '')
                . 'dbname=' . $this->config['database'];
        } elseif ($this->config['driver'] == 'sqlite') {
            $this->dsn = 'sqlite:' . $this->config['database'];
        }
        
        $this->db = Database::initialize(
            'pdo', [
                $this->dsn,
                $this->config['user'],
                $this->config['pass'],
                $this->config['opts']
            ],
            'ezDb'
        );
        return $this->db;
    }
    
    public function tearDown()
    {
        $this->db = null;
    }
```
I need to know if I am initializing correctly. When I instantiate the class and call `$db->setUp()`, according to the tests, I expect it to show some autocomplete methods, one of which being `->connect()` which will then become `$db->setup()->connect(....)`, but no list of usable methods show up. So, I am figuring that I am doing something wrong.

**Comment by techno-express** [comment]
I'm not really following what you are trying to accomplish. 

You might what to read up on php testing google `phpunit tutorial`. Then look at tests again. What you have is not like the tests library at all. 

You can't instantiate the class with `$db->setUp()`; you don't even call it at all. `->setup()` is part of phpunit, and `->connect(....)` is an method of ezSQL driver library, which would be `$this->db->connect(....)`, that you actually don't really need to call because it will be called automatically if there is no connection established.

**Comment by parkerj** [comment]
Ok, let me put it another way.

In my config.php file, I have the following:

```php
$db = Database::initialize(
    'pdo', [
        $config['dsn'],
        $config['user'],
        $config['pass'],
        $config['opts']
    ],
    'ezDb'
);
```
Is the above code correct? If so, my IDE's autocomplete/intellisense isn't showing me what methods I can use with $db? If my code above isn't correct, what am I doing wrong?

**Comment by techno-express** [comment]
That's correct

**Comment by techno-express** [comment]
use this way instead, it my be the way the IDE seeing it.
```
use ezsql\Config;
use ezsql\Database\ez_****;

$setting = new Config('****', [$dsn_path_user, $password, $database, $other_settings]);

$db = new ez_****($settings);
```

**Comment by parkerj** [comment]
Yes, that way works, but I was hoping to have the other way work instead. Thanks.

**Comment by techno-express** [comment]
I use VS Code, most of the time it shows up either way.

**Comment by parkerj** [comment]
Ok, I will try a different IDE.
