### ISSUE TITLE
Uncaught Error: Call to a member function prepare() on null 

### ISSUE THREAD

**Issue by marcusstahl** [ezSQL/ezsql#157]
Hi,
I've been struggling for a couple of hours now trying to get any of the prepared methods to work. And I can't get it to work in anyway. I use composer for the install. 

I run more or less this code: (I have some environment variables etc outside of that but it all works with a simple $db->get_result, etc just not the prepared methods.

Any idea if there is some bug? I've been copy pasteing, checking the tests code etc but can't get it to work.

require 'vendor/autoload.php';
use ezsql\Config;
use ezsql\Database\ez_mysqli;

$settings = new Config('mysqli', [DB_USR, DB_PASSWORD, DB_NAME, DB_ADDRESS]);
$db = new ez_mysqli($settings);

$db->show_errors();

$string = "TsklqnLP77URbwBx";

$db->prepareOff(); //Tried with both on and off.
$db->query_prepared('SELECT mycolumn FROM mytable WHERE mywherecolumnd = ?', [$string]);
$result = $db->queryResult();

echo $db->debug();

Getting error:
Fatal error: Uncaught Error: Call to a member function prepare() on null in /var/www/myfolder/vendor/ezsql/ezsql/lib/Database/ez_mysqli.php:274 Stack trace: #0 /var/www/myfolder/myfile.php(39): ezsql\Database\ez_mysqli->query_prepared('SELECT mycolumn ...', Array) #1 {main} thrown in /var/www/myfolder/vendor/ezsql/ezsql/lib/Database/ez_mysqli.php on line 274

I run PHP Version 7.1.28 (Started on 7.3 but have downgradeing to make sure)

**Comment by techno-express** [comment]
You are missing needed info:
What ezsql version you using? Current is v4.0.4 that has some bug fixes related to `query_prepared`
Need actually code snipped you used? 

The test you need to reference or copy is: https://github.com/ezSQL/ezsql/blob/0d3bdf2f15a3399d1669b966fdef601d1e5ec75f/tests/mysqli/mysqliTest.php#L579

Turn debug on with `$db->setDebug_Echo_Is_On(true);` then just `$db->debug();`

Anyway, you have something going on in your code, can't tell from what you submitted and the phpunit tests cover `query_prepared` as listed above as passing on PHP 7.1, 7.2, and 7.3, Also PHP 7.0 which i use locally.

That error means you don't have an valid object or the database handle resource.

I'm closing this for now, reopen with necessary info.
