### ISSUE TITLE
$db->num-rows doesn't work

### ISSUE THREAD

**Issue by celikbas** [ezSQL/ezsql#158]
**Describe the bug**
$db->num-rows seems not to work, probably because of php version. Also $db->debug system seems not to work.

I need to know the returned record number. Is there any way to do this :-)
Thanks.

Zeki

> *Warning*: 
 Warning: Use of undefined constant rows - assumed 'rows' (this will throw an Error in a future version of PHP) in /opt/lampp/htdocs/kits/common/system/pageditor.php on line 53

**Environment (please complete the following information):**
 - EZSQL Version : 4
 - PHP Version: 7.3
 - SQL Driver: mysqli

**PHP code snippet used**
```php
<?php
$result = $db->query($sql)
if ($db->num-rows > 0) {
    echo "There are X waiting request";
}


```

**Comment by jv2222** [comment]
It’s num_rows not num-rows ie it needs an underscore....

**Comment by celikbas** [comment]
Hi
> It’s num_rows not num-rows ie it needs an underscore....

Now, I've tried as num_rows but I've got the following error:

`Fatal error: Uncaught Error: Cannot access protected property ezsql\Database\ez_mysqli::$num_rows`

By the way in Documentation (https://github.com/ezSQL/ezsql/wiki/Documentation) it writes as $db->num-rows it needs to be corrected.

**Comment by techno-express** [comment]
>$result = $db->query($sql)
if ($db->num-rows > 0) {
    echo "There are X waiting request";
}


Just read want you have, you are getting the correct error. If you want access it will need to be by `$db->getNum_Rows()`. All those properties are now protected by design. 

The doc's page have been converted from html page to markdown using some online tool. Everything needs underscore, and that just a manual time consuming process to get done.

**Comment by jv2222** [comment]
Hmm, underscores in method names?

 IMHO it would look better like $db->getNumRows() same for all methods!

**Comment by techno-express** [comment]
Yes, it's one of those breaking changes debating about. It is in the plans,
I have an todo routine in ezsqlModel.php __call method to handle that. But
then afterwards the tests needs to be updated, otherwise failing tests

**Comment by myosotisgit** [comment]
The docs/wiki has not been updated, but most, if not all, db functions are now changed to 
$db->getXxxXxx(). The methods mentioned in the database, for example $db->num_rows is now 'protected' and can be accessed with $db->getNumRows();

**Comment by techno-express** [comment]
Yes, it needs updating, I just haven't had the time/desire to do so.

**Comment by myosotisgit** [comment]
@techno-express 

We are just implementing v4 into an web application. Maybe we can add some findings to the docs ?

**Comment by techno-express** [comment]
Yes, the PR, will be very appreciated!

I'm really in maintenance mode with this library at the moment. There are many todo's/additional features that needs implementing. 

Kind of expecting other contributors to fill in. I have this library doing what I need it for at the moment, and fixing any bug issues others raise.
