### ISSUE TITLE
Escape function bug 

### ISSUE THREAD

**Issue by agarassino** [ezSQL/ezsql#161]
I'm getting an error while trying to use $db->escape(string):

**PHP Fatal error:  Uncaught TypeError: mysqli_real_escape_string() expects parameter 1 to be mysqli, null given in /home/daisy/public_html/vendor/ezsql/ezsql/lib/Database/ez_mysqli.php:180**

 - EZSQL Version : 4
 - PHP Version: 7.0.33
 - SQL Driver: mysqli

Any ideas? 
Thanks!

**Comment by techno-express** [comment]
**Will need an example of the code used.** 
However, the error means you don't have an database connection handle. The first parameter is an resource instance returned after **mysqli** makes an successful database connection. So connection was closed or nulled somewhere.

Also you should do an `composer update`, **ezsql** at 4.0.5

**Comment by agarassino** [comment]
Thanks for the reply. I'm using 4.0.5
Im using this code to connect and query the db:

```
use ezsql\Config;
use ezsql\Database\ez_mysqli;
$setting = new Config('mysqli', [getenv("DB_USER"), getenv("DB_PASS"), getenv("DB_NAME"), getenv("DB_HOST")]);
$db = new ez_mysqli($setting);

$db->query_prepared('SELECT name, email FROM ms_members WHERE id = ?', [1]);

$result = $db->queryResult();
```

And i get this in the error_log:

PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in /home/daisy/public_html/vendor/ezsql/ezsql/lib/Database/ez_mysqli.php:275

Db credentials are ok, its like it wont save the handler into the db object. Any hint ?

**Comment by techno-express** [comment]
As reference here https://github.com/ezSQL/ezsql/issues/157

You are submitting full sql statements not using the query shortcut calls. As such, you also need to make sure you call $db->connect(); and $db->select() these methods are call automatically by the other query methods. If you don't, you will most definitely get the error you have.
