### ISSUE TITLE
Grouping WHERE conditions with ezSQL v4 PDO

### ISSUE THREAD

**Issue by dpDesignz** [ezSQL/ezsql#164]
I know this is probably going to be very obvious, but can anyone please show me how to group my `WHERE` conditions when using the `selecting` function? I know how to write it in standard SQL, but I can't for the life of me work this out using ezSQL.

What I'm wanting

`SELECT user_id, user_password, user_password_key FROM users WHERE (user_login = $userData OR user_email = $userData) AND user_status=1`

What I've tried

```
$db->selecting('users', 'user_id, user_password, user_password_key', where(eq('user_status', '1', _AND)), where(eq('user_login', $userData, _OR ), eq('user_email', $userData )));

$db->selecting('users', 'user_id, user_password, user_password_key', where(eq('user_status', '1')), where(eq('user_login', $userData, _OR ), eq('user_email', $userData )));

$db->selecting('users', 'user_id, user_password, user_password_key', $db->where(eq('user_login', $userData, _OR ), eq('user_email', $userData )), $db->where('user_status', '1'));

$db->selecting('users', 'user_id, user_password, user_password_key', eq('user_login', $userData, _OR ), eq('user_email', $userData ), $db->where('user_status', '1') );
```

It works if I remove the condition for the `user_status`, but when it's in there it just returns `NULL`.

**Comment by techno-express** [comment]
need just one where statement like **`where(eq(x, y, if_another), ne(same), gt(same),...)`**

**Comment by dpDesignz** [comment]
> 
> 
> need just one where statement like **`where(eq(x, y, if_another), ne(same), gt(same),...)`**

I tried the following code:

`$db->selecting('users', 'user_id, user_password, user_password_key', where(eq('user_status', '1', _AND), eq('user_login', $userData, _OR ), eq('user_email', $userData )));`

Which gave me the following debug:

`SELECT user_id, user_password, user_password_key FROM users WHERE user_status = ? AND user_login = ? OR user_email = ? `

The issue is I need the `user_login` and `user_email` grouped with the OR statement because I want it to check if the entered data matched their username OR their login name AND they are an active user. Currently this returns a result even if the email address matches but the user _status is 0, just like SQL normally would. I need the where statement to be grouped in parenthesis like my original example:

`SELECT user_id, user_password, user_password_key FROM users WHERE (user_login = $userData OR user_email = $userData) AND user_status=1`

How do I do this please?

**Comment by techno-express** [comment]
You will need to test your SQL statement the regular way, no shortcuts.
I don't believe it's valid for what you are trying to retrieve. `$userDate` for both **user_login**  and **user_email** 
Where is an working **Grouping** example where it works, like you have it?

**Comment by dpDesignz** [comment]
My original example is standard SQL formatting. Examples [here](https://codepedia.info/sql-using-parentheses-with-and-or-condition-is-necessary-with-where-clause-to-gives-expected-result/) and [here](https://www.techonthenet.com/sql/and_or.php) for how this works.

`SELECT user_id, user_password, user_password_key FROM users WHERE (user_login = $userData OR user_email = $userData) AND user_status=1`

This is the code I'm using for now and it works, but I'd still like to know how to do it in the format above because I know I'll be using it soon.

`$result = $db->get_row("SELECT user_id, user_password, user_password_key, user_auth_rqd FROM users WHERE (user_login='$userData'  OR user_email='$userData') AND user_status=1");`

Here's an example of my table

```
+-----------------+------------------------+--------------------------------------------------------------+-------------------------------+-------------------------+------------------------+
| user_id int(11) | user_login varchar(60) | user_password varchar(75)                                    | user_password_key varchar(25) | user_email varchar(100) | user_status tinyint(1) |
+-----------------+------------------------+--------------------------------------------------------------+-------------------------------+-------------------------+------------------------+
| 1               | dpdesignz              | $2y$10$0WwGTXNWuqR/HMB4iZ6.quDsy/TG9FAkvQb3FAIS5mEw4mC5wHA03 | 7deqp5f799bncf55a7a3375e      | webmaster@dpdesignz     | 1                      |
+-----------------+------------------------+--------------------------------------------------------------+-------------------------------+-------------------------+------------------------+
```

So for example, on my login page, the user can enter EITHER a email address (user_email) OR a username (user_login). The SQL is supposed to check what they enter and see if it matches EITHER a username (user_login) OR a user email (user_email) in the database, AND if it finds a match it will THEN check to make sure that the user is active (user_status=1). This is a standard statement in SQL used everywhere.

**Comment by techno-express** [comment]
I see, will need to add another method or refactor for parenthesis grouping in `->where()`, to account for that type of condition.

**Comment by dpDesignz** [comment]
> 
> 
> I see, will need to add another method or refactor for parenthesis grouping in `->where()`, to account for that type of condition.

I'm only just learning OOP now and the code is a bit confusing still, otherwise I'd offer to help with this. Sorry.

May I suggest if there is the option to have multiple `where()` methods in a query, to group them with parenthesis by default? So maybe if I wrote a query like this

`$db->selecting('users', 'user_id, user_password, user_password_key', where(eq('user_login', $userData, _OR ), eq('user_email', $userData ), _AND), where(eq('user_status', '1')));`

_Note in the first `where()` the `_AND` is after the closing parenthesis for the second `eq()` method._

It would output as required

`SELECT user_id, user_password, user_password_key FROM users WHERE (user_login = $userData OR user_email = $userData) AND (user_status=1)`

Just an idea. Not sure how easy it would be to implement though.
