### ISSUE TITLE
Connection closing required when finished with db (PDO)

### ISSUE THREAD

**Issue by dpDesignz** [ezSQL/ezsql#165]
I've been looking through the methods file and was just wondering if there's any requirement to unset the database connection when finished with it? I've been reading up and some people say you should and others say you shouldn't. What's best practice here?

Example code:

```php
// Initialise connection 
$db = Database::initialize('pdo', ['mysql:host=localhost;dbname=example;charset=utf8mb', 'user', 'password']);

// Add some code in here to do what you want
...

// Close connection
$db = null;
```

**Comment by techno-express** [comment]
That's not closing the connection, that's destroying the local copy of the pdo class instance, There is still an global copy in `getInstance()`, doing `clearInstance()`, will destroy. 

Anyway the connection is open and close when necessary. This library automating a lot of things you would normally do manually.
