### ISSUE TITLE
Create a backwards-compatible layer with camelCase function names

### ISSUE THREAD

**Issue by pretzelhands** [ezSQL/ezsql#168]
**Is your feature request related to a problem? Please describe.**
I wouldn't call it a problem per se, but when using ezsql I have to break the PSR-2 formatting guidelines out of necessity, since functions are all named in `snake_case`

**Describe the solution you'd like**
I'd like to see a backwards compatible layer that aliases all `ezsqlModel` functions with `camelCase`d counterparts to ensure code style consistency with projects following PSR-2

**Describe alternatives you've considered**
I could probably write an aliasing layer myself, but it doesn't really seem like a smart move to do this, as you would also have to rewrite some internals to return the appropriate classes.

**Comment by techno-express** [comment]
I attempted to this for BC version, but realize there are just too many deprecation notices I would also need to implement. 

In short, to much work, too many places needs updating besides the tests. Someone else would need to do PR.
