### ISSUE TITLE
rows-affected variable does not exist

### ISSUE THREAD

**Issue by dpDesignz** [ezSQL/ezsql#169]
**Describe the bug**
In the documentation, there is [a reference to a variable](https://github.com/ezSQL/ezsql/wiki/Documentation#ezsql-variables) that can be called with `$db->rows-affected`, but I can't seem to find this anywhere in the code or how to execute it. I'm suddenly needing this. Has it changed? Or where can I find it?

**To Reproduce**
Try any of the following

`$db->rows-affected`
`$db->rows_affected`
`$db->getRows_Affected`

**Expected behavior**
Expected a number of total rows affected by my INSERT, DELETE, or UPDATE query

**Environment (please complete the following information):**
 - EZSQL Version : the constant in my files says 4.0.5, but I'm pretty sure composer said it's 4.0.7? (This probably needs to be somewhere easy to check? Or I'm just looking in the wrong place?)
 - PHP Version: 7.3.1
 - SQL Driver: PDO MySQL

**PHP code snippet used**

```php
$db->rows-affected();
$db->rows_affected();
$db->getRows_Affected();
```

**Comment by dpDesignz** [comment]
Just been digging in the code and found `affectedRows()`. I think this is the new variable? Can you please confirm @techno-express and I'll update the documentation to reflect this. 😄

**Comment by techno-express** [comment]
yes, the protected property is `$_affectedRows`, and the method `affectedRows()` will return it's value.

**Comment by dpDesignz** [comment]
Thanks. I spent a few hours updating the wiki last night and have changed it to the `affectedRows()` variable. 😄
