### ISSUE TITLE
Cached queryResult() ?

### ISSUE THREAD

**Issue by agarassino** [ezSQL/ezsql#173]
**Describe the bug**
Sometimes the library seems to be caching resultsets from previous calls. Im providing an example 

**To Reproduce**
`$db->query_prepared("SELECT *, id as mid FROM " . $prefix . "members WHERE id = ?", [$memberId]);

$resultQuery = $db->queryResult();
$memberArray = (array) $resultQuery['0'];

$db->query_prepared("SELECT * FROM ms_credentials WHERE mid = ? LIMIT 1;", [$memberid]);
$queryResults = $db->queryResult();
$credentials = (array) $queryResults['0']; //$credentials has the info from $memberArray!
`

**Environment (please complete the following information):**
 - EZSQL Version : 4
 - PHP Version: 7.1
 - SQL Driver: mysqli

**Comment by techno-express** [comment]
As indicated in issue https://github.com/ezSQL/ezsql/issues/171, https://github.com/ezSQL/ezsql/issues/165, and https://github.com/ezSQL/ezsql/issues/157, the user is responsible for everything when using `query_prepared()` directly, you need to call `flush()` to clear cached results. That too is done automatically when using the shortcut methods.

**Comment by agarassino** [comment]
Thanks!
