### ISSUE TITLE
getNum_Rows() returning 1 even though there are no results

### ISSUE THREAD

**Issue by dpDesignz** [ezSQL/ezsql#177]
**Describe the bug**
When running a `selecting()` that returns no results, `getNum_Rows()` is returning `1` and I'm not sure where from

**To Reproduce**
Run selecting with 2 left joins and a where statement.
Run `getNum_Rows()`

**Expected behavior**
If there are no results, I expect `getNum_Rows()` to return 0, but for some reason it does not. I don't have this issue on any of my other queries that are even more complex than this. It just seems to be this one. I've run a debug on it and even before the query runs the `$this->num_rows` has a value of 1. It seems to be in the `ez_pdo` file on roughly line 310 , this code `$this->num_rows = empty($num_rows) ? $this->num_rows : $num_rows;` isn't updating because `empty()` will return true if `$num_rows` is `0`. I have added `$this->num_rows = 0;` on line 262 in `ezsqlModel` in the `flush()` function which seems to have fixed the issue, but before I do a pull request I want to make sure I'm not missing anything?

I've also run `debug()`  which outputs "No Results" and `getNum_Rows()` which output "No rows returned".

**Environment (please complete the following information):**
 - EZSQL Version : 4.0.8
 - PHP Version: 7.3.9
 - SQL Driver: pdo:mysql

**PHP code snippet used**

_My selecting query:_
```php
selecting("me_product_category_path AS cp", "cp.pcp_category_id AS category_id, c1.category_name AS category_name, GROUP_CONCAT(c2.category_name ORDER BY cp.pcp_level SEPARATOR '&nbsp;&nbsp;&gt;&nbsp;&nbsp;') AS category_path, c1.category_description, c1.category_parent_id, c1.category_sort_order, c1.category_type, c1.category_status", leftJoin("cp", "me_product_category", "pcp_category_id", "category_id", "c1"), leftJoin("cp", "me_product_category", "pcp_category_parent_id", "category_id", "c2"), groupBy("cp.pcp_category_id"), orderBy('category_sort_order', 'ASC'), limit(0, 25);
```

_My compiled query:_
```sql
SELECT cp.pcp_category_id AS category_id, c1.category_name AS category_name, GROUP_CONCAT(c2.category_name ORDER BY cp.pcp_level SEPARATOR '  >  ') AS category_path, c1.category_description, c1.category_parent_id, c1.category_sort_order, c1.category_type, c1.category_status FROM me_product_category_path AS cp LEFT JOIN me_product_category AS c1  ON cp.pcp_category_id = c1.category_id LEFT JOIN me_product_category AS c2  ON cp.pcp_category_parent_id = c2.category_id GROUP BY cp.pcp_category_id ORDER BY category_path, category_sort_order ASC LIMIT 25
```
I have run this exact query in phpMyAdmin and it gives me the same result

**Comment by techno-express** [comment]
I think you should start learning the `phpunit` testing suite. 

This issue too make use of **joins**, that currently have no tests associated. I can only say your solution will only be correct if so proven. You need to track down where that 1 result is coming from. In `query_prepared` is the only place it's getting set. 

I'm currently not using `JOIN`s in any projects. Otherwise, i would have already been motivated in creating a phpunit test. 

When I started using, and working of this library there where no tests, and many, many bugs, some posted, that only revealed themselves once I started testing. I got this library now to a state that it does what i need it do, so I'm in maintenance mode handling major issues. 

There are still many things that needs to be done, but i really expect other contributors for those improvements to happen. Any contributors **PR**, if it does not cause code coverage to drop, i would just merge. Otherwise, i expect a test to cover **PR**.

**Comment by dpDesignz** [comment]
Fair enough. I will try my best to learn how to use `phpunit` this week and get a test put together. It's easy enough to write the code, I just couldn't work out how to actually run the test and read it.

The odd thing with it, I did mention the join just to show the code I have, but when I ran the debug in my IDE the `$this->num_rows` property already had a value of `1` before it even started doing anything with my query. So before it even started processing the joins. I've just had an idea of how to do a debug further up the stack so will see if that gives me any results, but from what I can tell so far it seems like it is leaking from somewhere else. I'll see how I can get on with some more debugging and will try work out `phpunit`.

I'm more than happy to contribute as much as I can to help build it up as it's a great library (I mean WordPress based their system off the original so who wouldn't want to. I'm surprised there aren't more contributors to be honest), but I'm just still learning this stuff as I have only just started getting into the heavier side of development even though I've been using PHP for 10 years.

**Comment by techno-express** [comment]
>but from what I can tell so far it seems like it is leaking from somewhere else.

You might be pulling up cache. 
The cache method `get_cache()`, is one other place it's getting set at. 
Are you using `prepareOn()` or calling `query_prepared()` directly?

If you are, try with it off, see what happens with the default escaping values instead.

The fetch before line 310 here:
The `$this->num_rows = empty($num_rows) ? $this->num_rows : $num_rows;` 
`$row` and `$num_rows` will actually not return anything cause any result would have be already retrieved, so `$this->num_rows` at this point will have some value from `query_prepared` fetch results.

You could do `var_dump/print_r` at line 304, see state of the variables/properties.

**Comment by dpDesignz** [comment]
Just an update on this, I've found that running `flush()` before my `query_prepared()` helps with this issue

**Comment by techno-express** [comment]
As i indicated elsewhere, when using `query_prepared()` outside of the shortcut methods, the **user/developer** is _responsible for everything_, no checks are made, so `flush` is always executed.

**Comment by dpDesignz** [comment]
Are you meaning it's already executing, or that I need to always manually be executing it?

**Comment by techno-express** [comment]
I mean when you use the shortcut methods that function always called.
