### ISSUE TITLE
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP

### ISSUE THREAD

**Issue by salimonhakym** [ezSQL/ezsql#178]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; ezSQLcore has a deprecated constructor in C:\xampp\htdocs\eazy\lib\ezsql\ez_sql_core.php on line 27

Deprecated: define(): Declaration of case-insensitive constants is deprecated in C:\xampp\htdocs\eazy\lib\ezsql\ez_sql_core.php on line 18

Deprecated: define(): Declaration of case-insensitive constants is deprecated in C:\xampp\htdocs\eazy\lib\ezsql\ez_sql_core.php on line 19

Deprecated: define(): Declaration of case-insensitive constants is deprecated in C:\xampp\htdocs\eazy\lib\ezsql\ez_sql_core.php on line 20

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; ezSQL_mysql has a deprecated constructor in C:\xampp\htdocs\eazy\lib\ezsql\ez_sql_mysql.php on line 31
Fatal Error: ezSQL_mysql requires mySQL Lib to be compiled and or linked in to the PHP engine
> *Warning*: Failing to provide necessary information may cause the issue to be closed without consideration

**Environment (please complete the following information):**
 - EZSQL Version : 
 - PHP Version:
 - SQL Driver:[ mysql, pgsql, sqlserver, sqlite3]

**PHP code snippet used**

```php
<?php


```

**Comment by techno-express** [comment]
You are using an unsupported version of this library. The errors indicate you are on version 1 or 2.

**Comment by techno-express** [comment]
What PHP version being used? This library requires at least 7.0, which no longer support mysql.
