### ISSUE TITLE
Minimum PHP version should be 7.1

### ISSUE THREAD

**Issue by nemo9l** [ezSQL/ezsql#182]
In composer.json, the minimum PHP version is manifested by 7.0

But, Nullable types(like ?string) cannot use on PHP 7.0. That features are added after 7.1.
(Refer to https://www.php.net/manual/en/migration71.new-features.php)

---
Sorry for bad english. Korean version attached.

composer.json 에서 PHP 최소버전이 7.0으로 명시되어 있습니다.
그러나, ?string 과 같은 Nullable 타입 선언의 경우 PHP 7.1 부터 사용이 가능합니다.
https://www.php.net/manual/en/migration71.new-features.php 참고 바랍니다.

**Comment by nemo9l** [comment]
Nullable types was used in ./lib/Database.php only.
You should change nullable-typed code to nullable-type-excluded code.

---
Nullable 타입 선언이 ./lib/Database.php 에만 사용되었네요.
해당 코드를 Nullable 타입선언이 사용되지 않은 코드로 변경하는 것이 좀 더 나은 방향같습니다.

**Comment by techno-express** [comment]
Yes, you are correct. 
The Travis CI build allowed that version fail and ignore the result. Will be updating composer.json and travis.yml for PHP 7.1+
