### ISSUE TITLE
Initializing database error

### ISSUE THREAD

**Issue by similarduckweed** [ezSQL/ezsql#187]
erro：
"<br />
<b>Fatal error</b>:  Uncaught ezsql\Exception\ContainerException: Can not resolve class dependency dsn in D:\phpstudy_pro\WWW\duwell\vas-cas-admin\common\vendor\ezsql\ezsql\lib\DInjector.php:144
Stack trace:
#0 D:\phpstudy_pro\WWW\duwell\vas-cas-admin\common\vendor\ezsql\ezsql\lib\DInjector.php(112): ezsql\DInjector-&gt;getDependencies(Array, Array)
#1 D:\phpstudy_pro\WWW\duwell\vas-cas-admin\common\vendor\ezsql\ezsql\lib\DInjector.php(50): ezsql\DInjector-&gt;resolve('PDO', Array)
#2 D:\phpstudy_pro\WWW\duwell\vas-cas-admin\common\vendor\ezsql\ezsql\lib\Database.php(50): ezsql\DInjector-&gt;get('PDO', Array)
#3 D:\phpstudy_pro\WWW\duwell\vas-cas-admin\login\login.php(12): ezsql\Database::initialize('PDO', Array)
#4 {main}
  thrown in <b>D:\phpstudy_pro\WWW\duwell\vas-cas-admin\common\vendor\ezsql\ezsql\lib\DInjector.php</b> on line <b>144</b><br />
"

**Comment by techno-express** [comment]
You have not provide any necessary info, none of the required, no code snippet, no bug report.

**As such look over the tests, then reopen.**

**Comment by similarduckweed** [comment]
`<?php
/**
 * Test Doc
 *
 * PHP version 7
 *
 * @category Duwell
 * @package  Vascasweb
 * @author   miller <miaoyangzhi@163.com>
 * @link     Http://www.duwell.com
 */
//require_once '../common/PDO.php';
require '../common/vendor/autoload.php';
use ezsql\Database;

//实例化类
$id = 1;
$sql = "select account from user where id=1";
/* $data = $pdo->query($sql, $queryMode = 'Row', $debug = false); */
$db= Database::initialize('PDO', ['mysql:host=localhost;dbname=duwell;port=3306','root','root']);

$data=$db->query($sql);`

**Comment by similarduckweed** [comment]
Is there a problem connecting to the database？

**Comment by techno-express** [comment]
> require '../common/vendor/autoload.php';

What is that?
Look at the `readme.md` examples.
You are getting the correct error, there is no error. 
You are using composer autoload wrong.

If that what the case none of the tests would be passing.
