### ISSUE TITLE
$db->query_prepared() not working or misleading documentation 

### ISSUE THREAD

**Issue by vCiKv** [ezSQL/ezsql#188]
**Describe the bug**
the php output says:
Fatal error: Uncaught Error: Call to a member function prepare() on null in C:\xampp\htdocs\Visual Studio\mat\php\lib\vendor\ezsql\ezsql\lib\Database\ez_mysqli.php:277 Stack trace: #0 C:\xampp\htdocs\Visual Studio\mat\a\test.php(168): ezsql\Database\ez_mysqli->query_prepared('SELECT Password...', Array) #1 {main} thrown in C:\xampp\htdocs\Visual Studio\mat\php\lib\vendor\ezsql\ezsql\lib\Database\ez_mysqli.php on line 277

**To Reproduce**
i ran the php code below and used a different query same result 

**Expected behavior**
i expect the values of the database to be displayed using prepared statements 

**Environment (please complete the following information):**
 - EZSQL Version : ^4.0
 - PHP Version: 7.4.1
 - SQL Driver: mysql

**PHP code snippet used**

```php
<?php
$db = Database::initialize('mysqli', [$dbusername, $dbpassword, $dbname, '']);
$db->debugOn();
// $db->query_prepared('SELECT `First Name`,`E-mail` FROM `users` WHERE ID > ?', [3]); 
//both queries give the same error
$db->query_prepared('SELECT Password, email FROM users WHERE phone = ? OR id != ?', [3, 5]);
$result = $db->queryResult(); 
foreach ($result as $row) {
    echo $row->Password.' '.$row->email;
}
$db->debug();
echo '<pre>';
print_r($result);


```

**Comment by techno-express** [comment]
> Fatal error: Uncaught Error: Call to a member function prepare() on null in

That means you do not have an database instance object, `$db` is not valid.

run a check 
```
if ($db instanceof DatabaseInterface) {
  // your code
}
``

**Comment by techno-express** [comment]
Also read:
https://github.com/ezSQL/ezsql/issues/177, https://github.com/ezSQL/ezsql/issues/171. https://github.com/ezSQL/ezsql/issues/173

**Comment by vCiKv** [comment]
thank you for the comment the issue was simple i just needed to add 
```php 
$db -> connect();
```
and it was working as expected i just wish the documentation would make it easier for new programmers

**Comment by techno-express** [comment]
The docs needs updating to state **"you are responsible for everything when using `query_prepared()` outside of the shortcut methods"**. 

It's an internal method, checks are made before being called. It was made public for some who wish to use nothing else but just that. In which case, you have done what would have been called otherwise. 

Some like to repeat everything what the shortcut methods is doing. 

This package is base on the shortcut methods, DRY.
