### ISSUE TITLE
mysql functions on where method

### ISSUE THREAD

**Issue by ogunbaysal** [ezSQL/ezsql#189]
Is that possible to use mysql functions such as date_add with between function ?

**Comment by techno-express** [comment]
I don't see why that shouldn't work. 

Have you tried, and what was the error/result?
Do you have some code snippet to check/test with?

**Comment by ogunbaysal** [comment]
No error but result is with quotes. When it generates the between sql query you add single quote both before and after of values. Because of that mysql see them as string and doesnt work mysql functions.

**Comment by techno-express** [comment]
Does it produce same result with `->prepareOn();`?

It's will need an example you have to create a method or adjust current ones to detect if function is beginning used.

I need a full **SQL statement** to showing the functions used that way, and expected result from it.
