### ISSUE TITLE
how to connect to unsupported oracle8_9 datbase?

### ISSUE THREAD

**Issue by bunkford** [ezSQL/ezsql#193]
how to connect to unsupported oracle8_9 database?

**Comment by techno-express** [comment]
Take a look at the tests:
https://github.com/ezSQL/ezsql/blob/c843017092b861e14c3f92ee2b98057d4c42f872/unsupported/tests/oracle8_9/ezSQL_oracleTNSTest_.php#L63
https://github.com/ezSQL/ezsql/blob/c843017092b861e14c3f92ee2b98057d4c42f872/unsupported/tests/oracle8_9/ezSQL_oracle8_9Test.php#L193

The reason for unsupported is that there is no automated way to install the program with database setup. 
It might be time to remove them from this Repo.
