### ISSUE TITLE
Error when running composer

### ISSUE THREAD

**Issue by TrevorRoberts** [ezSQL/ezsql#194]
Hi,
I first used ezSQL when it first came out. I just downloaded it again today and see that I must use composer to install it. I immediately got an error saying: 

"Root package 'ezsql/ezsql' cannot require itself in its composer.json".

I miss the old day when you could just download something and include it without being forced to load all kind of frameworks and other junk. 

I got the error after installing GitHub Desktop and Composer then running "composer require ezsql/ezsql". 

Thanks in advance.
Trevor

**Comment by techno-express** [comment]
Delete your '**composer.json**' file or do '**composer update ezsql/ezsql**' instead.

**Comment by TrevorRoberts** [comment]
Thank you very much!
