### ISSUE TITLE
Multi-table syntax Examples

### ISSUE THREAD

**Issue by scottynorris** [ezSQL/ezsql#195]
Maybe I'm missing something, but I've searched _high and low_ and cannot find any examples for **multi-table syntax**?

What I'm looking for specifically is how to complete something similar to this:
```
UPDATE config t1 JOIN config t2
    ON t1.config_name = 'name1' AND t2.config_name = 'name2'
   SET t1.config_value = 'value',
       t2.config_value = 'value2';
```
**And/or conditional updating:**

```
UPDATE config
   SET config_value = CASE config_name 
                      WHEN 'name1' THEN 'value' 
                      WHEN 'name2' THEN 'value2' 
                      ELSE config_value
                      END
 WHERE config_name IN('name1', 'name2');
```

Thanks!

**Comment by techno-express** [comment]
Here is the closest test referencing using the shortcut methods of [Join](https://github.com/ezSQL/ezsql/blob/c843017092b861e14c3f92ee2b98057d4c42f872/lib/ezQuery.php#L287) that can be used as a **example** added by @dpDesignz 
https://github.com/ezSQL/ezsql/blob/c843017092b861e14c3f92ee2b98057d4c42f872/tests/pdo/pdo_mysqlTest.php#L288
https://github.com/ezSQL/ezsql/blob/c843017092b861e14c3f92ee2b98057d4c42f872/tests/pdo/pdo_pgsqlTest.php#L210
https://github.com/ezSQL/ezsql/blob/c843017092b861e14c3f92ee2b98057d4c42f872/tests/pdo/pdo_sqliteTest.php#L239
https://github.com/ezSQL/ezsql/blob/c843017092b861e14c3f92ee2b98057d4c42f872/tests/pdo/pdo_sqlsrvTest.php#L214

**Comment by scottynorris** [comment]
Thanks!
