### ISSUE TITLE
Dead fork of ezSQL?

### ISSUE THREAD

**Issue by OscarWilde** [ezSQL/ezsql#196]
I found some missing aspects in this fork of ezSQL. But I think, nothing will happen here anymore. Is that correct?

**Comment by techno-express** [comment]
What do you mean? Dead fork of what? 

This is the main repo.

**Comment by OscarWilde** [comment]
I'm missing for e.g. some kind of documentation. There are some methods that are not described at all. I thought this project is not maintained anymore.

**Comment by techno-express** [comment]
What made you figure not maintained? Did you see commit history? And what methods?
Most are in doc-blocks if using IDE, then there is the wiki and readme.

**Comment by dpDesignz** [comment]
> I'm missing for e.g. some kind of documentation. There are some methods that are not described at all. I thought this project is not maintained anymore.

What is missing from the documentation that you would like to see? I have been trying to re-write the wiki when I have time but haven't had a chance to recently. Let me know and I'll see what I can chuck up for you 😄

**Comment by SOM-Scott** [comment]
v3 is badly broken and not at all a drop-in for v2. Current project is v2 on PHP 8 and there were a few minor errors with v2 that caused a headache but v3 is much more badly broken on 8 then v2 was.

v4 is missing basic install instructions, there is no 'vendor/autoload.php' file to require in order to get going with the library.

**Comment by dpDesignz** [comment]
> v3 is badly broken and not at all a drop-in for v2. Current project is v2 on PHP 8 and there were a few minor errors with v2 that caused a headache but v3 is much more badly broken on 8 then v2 was.
> 
> v4 is missing basic install instructions, there is no 'vendor/autoload.php' file to require in order to get going with the library.

As the wiki documentation notes, [v2 and v3 are barely supported anymore](https://github.com/ezSQL/ezsql/wiki/Installation#version-2x), and v4 was a re-write and released as an update to support at least v7 of PHP. If you look at the wiki [there are instructions for getting started](https://github.com/ezSQL/ezsql/wiki/Installation), including how to [install it via composer](https://github.com/ezSQL/ezsql/wiki/Installation#version-4x-latest) which is required to install v4.

I'd suggest [reading up on composer](https://getcomposer.org/doc/00-intro.md) to understand how to get it installed and started. 😄 

If your project is quite large, unfortunately, there will be a lot of re-writing that will need to be done, but once you do that and you've wrapped your head around the [shortcut methods](https://github.com/ezSQL/ezsql/wiki/Shortcut-Methods), I think you'll find it much easier to use!
