### ISSUE TITLE
Setting Table Name and Prefix

### ISSUE THREAD

**Issue by Gokhank58** [ezSQL/ezsql#198]
**Describe the solution you'd like**
It might be nice to set the table name and prefix globally in advance.

**Additional context**
`
$ezsql->table('users_table', 'users_prefix_');

$ezsql->selecting(...)
`

**Comment by techno-express** [comment]
That's seems doable, but will require some internal routines structural changes, breaking changes. 

That should be targeted towards another major version update.

I just created another branch v5. If you want to submit PR, do so on that branch.

**Comment by techno-express** [comment]
Implemented in current release https://github.com/ezSQL/ezsql/releases/tag/5.0.0
