### ISSUE TITLE
Return 500 error while getting more than 100000 rows 

### ISSUE THREAD

**Issue by pradeep518** [ezSQL/ezsql#203]
**Describe the bug**
While getting data from the database, it is returning an HTTP 500 error.  

**To Reproduce**
A query that can return 100000 rows. 

**Expected behavior**
Getting the data without any error. 

**Environment (please complete the following information):**
 - EZSQL Version : 2.03 
 - PHP Version: 5.6
 - SQL Driver:[ mysql]

**PHP code snippet used**

```php
<?php


```

**Comment by techno-express** [comment]
You might want to try ezsql version 3x, it's compatible with PHP 5.6. 
There are many errors revealed in ezsql 2x, once PHPunit testing was added. They should have been fixed in version 3x branch.
