### ISSUE TITLE
Call to undefined function eq()

### ISSUE THREAD

**Issue by dpDesignz** [ezSQL/ezsql#204]
**Describe the bug**
Using the new version 5.1.1, I'm trying to understand how I'm supposed to set it up now. I've replaced the code I had with the new code from the example in the readme and in the tests file, but it's still giving me errors

**To Reproduce**
Update v4.0.12 to v5.1.1, change out use code to use new `use` for functions

**Expected behavior**
The new functions to work

**Environment (please complete the following information):**
 - EZSQL Version : 5.1.1
 - PHP Version: 7.4.4
 - SQL Driver: MySQL PDO

**PHP code snippet used**

Code that worked in v4
```php
require 'vendor/autoload.php';
// ** Load ezSQL Database Class ** //
use ezsql\Database;

class CornerstoneDBH extends ezsql\Database
{

  // Set the properties
  private $ezsql_type = EZSQL_TYPE;
  private $db_hostname = DB_HOSTNAME;
  private $db_name = DB_NAME;
  private $db_charset = DB_CHARSET;
  private $db_user = DB_USER;
  private $db_password = DB_PASSWORD;
  public $dbh;

  // Construct the DB
  public function __construct()
  {

    // Init the database connection
    $this->dbh = Database::initialize($this->ezsql_type, ['mysql:host=' . $this->db_hostname . ';dbname=' . $this->db_name . ';charset=' . $this->db_charset, $this->db_user, $this->db_password]);

    // Turn prepared statment support on
    $this->dbh->prepareOn();

    // Enable debug echoing
    $this->dbh->debugOn();
  }
}

// Load options from `cs_options` table where `autoload` is `true`
$csOptions = new CornerstoneDBH; // Init db connection
$row = null;
foreach ($csOptions->dbh->selecting(DB_PREFIX . 'options', array('option_name', 'option_value'), eq('autoload', '1')) as $row) {
	define(strtoupper($row->option_name), $row->option_value);
}
```

Code used now that's giving me the error

```php
require 'vendor/autoload.php';
// ** Load ezSQL Database Class ** //
use ezsql\Database;
use function ezsql\functions\{
  leftJoin,
  column,
  primary,
  grouping,
  like,
  where,
  eq
};

class CornerstoneDBH extends ezsql\Database
{

  // Set the properties
  private $ezsql_type = EZSQL_TYPE;
  private $db_hostname = DB_HOSTNAME;
  private $db_name = DB_NAME;
  private $db_charset = DB_CHARSET;
  private $db_user = DB_USER;
  private $db_password = DB_PASSWORD;
  public $dbh;

  // Construct the DB
  public function __construct()
  {

    // Init the database connection
    $this->dbh = Database::initialize($this->ezsql_type, ['mysql:host=' . $this->db_hostname . ';dbname=' . $this->db_name . ';charset=' . $this->db_charset, $this->db_user, $this->db_password]);

    // Turn prepared statment support on
    $this->dbh->prepareOn();

    // Enable debug echoing
    $this->dbh->debugOn();
  }
}

// Load options from `cs_options` table where `autoload` is `true`
$csOptions = new CornerstoneDBH; // Init db connection
$row = null;
foreach ($csOptions->dbh->selecting(DB_PREFIX . 'options', array('option_name', 'option_value'), eq('autoload', '1')) as $row) {
	define(strtoupper($row->option_name), $row->option_value);
}
```

The error that I'm getting

`Fatal error: Uncaught Error: Call to undefined function eq()`

Do I now have to load the `use function ezsql\functions\...` line at the top of EVERY file that uses ezSQL?? Before I only had to have `use ezsql\Database;` at the top of my database class file.

**Comment by dpDesignz** [comment]
So yes you do need to load the `use function ezsql\functions\...` line at the top of every file. I'll update the Wiki this weekend to explain how all the new features work now that I've wrapped my head around them better.

**Comment by techno-express** [comment]
First, i see another issue:
> foreach ($csOptions->dbh->selecting(DB_PREFIX . 'options', array('option_name', 'option_value'), eq('autoload', '1')) as $row) {
	define(strtoupper($row->option_name), $row->option_value);
}

The **->selecting()** behavior has changed to::
https://github.com/ezSQL/ezsql/blob/c97203b0ebb38bcb129bdba6fb6943972fc21dd8/lib/ezQuery.php#L928

Doc-block comments:
https://github.com/ezSQL/ezsql/blob/c97203b0ebb38bcb129bdba6fb6943972fc21dd8/lib/ezQueryInterface.php#L430
Check **readme** again at top, you need to call `->setTable()` or use `->select()` instead.

Besides that you should not be getting any errors, all tests been updated to use new format.

**Comment by dpDesignz** [comment]
> 
> 
> First, i see another issue:
> 
> > foreach ($csOptions->dbh->selecting(DB_PREFIX . 'options', array('option_name', 'option_value'), eq('autoload', '1')) as $row) {
> > define(strtoupper($row->option_name), $row->option_value);
> > }
> 
> The **->selecting()** behavior has changed to::
> 
> https://github.com/ezSQL/ezsql/blob/c97203b0ebb38bcb129bdba6fb6943972fc21dd8/lib/ezQuery.php#L928
> 
> Doc-block comments:
> 
> https://github.com/ezSQL/ezsql/blob/c97203b0ebb38bcb129bdba6fb6943972fc21dd8/lib/ezQueryInterface.php#L430
> 
> Check **readme** again at top, you need to call `->setTable()` or use `->select()` instead.
> 
> Besides that you should not be getting any errors, all tests been updated to use new format.

Thanks. Yea I understand that now. The new format was just confusing to wrap my head around as the `table_setup` function isn't really explained that well. I'll update the wiki to rectify that this weekend :)
