### ISSUE TITLE
Warning appears on query_prepared method.

### ISSUE THREAD

**Issue by thruthesky** [ezSQL/ezsql#206]
**Describe the bug**
Warning happens like below when `db()->query_prepared(...)` runs,
```
Warning:  ezsql\Database\ez_mysqli::ezsql\Database\{closure}(): Argument #2 ($arg) must be passed by reference, value given in /docker/home/centerx/vendor/ezsql/ezsql/lib/Database/ez_mysqli.php on line 307
```
**To Reproduce**

run the code below
```
$db->query_prepared(...)
```

**Expected behavior**

The warning should not appear.

**Environment (please complete the following information):**
 - EZSQL Version : 5.1
 - PHP Version: 8.0.3
 - SQL Driver: mysql

**PHP code snippet used**

```php
<?php
 $db->query_prepared(..., ...);
 $rows = get_results(ARRAY_A, $db);
```

**Comment by techno-express** [comment]
Read the **readme** on it's usage!

If you are using this directly you are responsible for all checks. It's part of the shortcut methods, all checks are done there.

The call take a **string**, and **array**, and it's really a private methods, made public.
