### ISSUE TITLE
Add disconnect function the can be initialized again in loop.

### ISSUE THREAD

**Issue by btafoya** [ezSQL/ezsql#207]
**Is your feature request related to a problem? Please describe.**
There is not currently a way to close the database connection, and be able to later initialize the connection again, which is needed for example with a php script that runs as a continuous loop or as a gearman worker process.

**Describe the solution you'd like**
Simply add a disconnect method; $db->disconnect()

`<?php
/*
 *  Gearman worker
 */
$worker = new GearmanWorker();
$worker->addServer();
$worker->addFunction("ImportData", function ($job) {

    $db = Database::initialize(DB_DRIVER, [
        DB_USERNAME,
        DB_PASSWORD,
        DB_DATABASE,
        DB_HOSTNAME,
        DB_PORT
    ]);

    // run the actual worker code here

    $db->disconnect();

    echo "\n\n[" . date("Y-m-d H:i:s") . "] Done: " . $job->handle() . "\n";
});
while ($worker->work());`

When the loop runs the next time, we see this message:

Warning: mysqli_close(): Couldn't fetch mysqli in vendor/ezsql/ezsql/lib/Database/ez_mysqli.php on line 464

MySQL 8/ PHP 7.3

**Comment by techno-express** [comment]
> Simply add a disconnect method; $db->disconnect()

The method is already available:
https://github.com/ezSQL/ezsql/blob/4bc6a254b7ac9d4856da343682c9af14cbec8909/lib/Database/ez_mysqli.php#L461 

It is part of the **DatabaseInterface** contract, and should be documented in **Wiki**. Not in **Readme**, since it's been available as of version 1.x.

**Comment by btafoya** [comment]
I am using it in the example above, but yet still running into an issue where the connection will not initialize when the loop repeats.

**Comment by techno-express** [comment]
Try `$db->connect();` since in the example you are explicitly disconnecting with `$db->disconnect();` or try some shortcut method to force connection, your example is doing **no actual database access**, just initialize, that preforms **no actual connection**.

**Comment by btafoya** [comment]
Thank you @techno-express!
