### ISSUE TITLE
Can't insert emoji in utf8mb4 table & column

### ISSUE THREAD

**Issue by ro78** [ezSQL/ezsql#210]
**Describe the bug**
I've upgraded to ezsql 5. Env is PHP 7.4, MariaDB 10.5.11
It was working fine on version 2 and 3 of ezSQL.

**To Reproduce**
Try insert 😁 character
Example:
$mysql->query("INSERT INTO `test` (`text`) VALUES ('😁')");
Result: PHP Warning:  Incorrect string value: '\xF0\x9F\x98\x81' for column `test`.`test`.`text` at row 1 in /home/dev/ezsql/vendor/ezsql/ezsql/lib/ezsqlModel.php on line 441

**Expected behavior**
Insert works

**Environment (please complete the following information):**
 - EZSQL Version : 5.1
 - PHP Version: 7.4
 - SQL Driver: mysqli

**PHP code snippet used**

```php
<?php
include_once("vendor/autoload.php");
use ezsql\Database;
$mysql = Database::initialize('mysqli', ['test', 'password', 'test', null, "utf8mb4"], null);
$mysql->query("INSERT INTO `test` (`text`) VALUES ('😁')");
?>
```

**Comment by ro78** [comment]
It works if I edit this in ConfigAbstract:
    private $charset = 'utf8mb4';

How can I set it in initialize? I tried to replace utf8 by utf8mb4 in my code but doesn't work.

**Comment by techno-express** [comment]
>$mysql = Database::initialize('mysqli', ['test', 'password', 'test', null, "utf8mb4"], null);

That is incorrect, you don't have **host** and **port**, **charset** is last parameter, 2 more before that.

>$mysql = Database::initialize('mysqli', ['test', 'password', 'test', $host, $port, "utf8mb4"]);

Look at docblock for layout:
https://github.com/ezSQL/ezsql/blob/4bc6a254b7ac9d4856da343682c9af14cbec8909/lib/Database.php#L47

**Comment by ro78** [comment]
You'right ! Thank you!
