### ISSUE TITLE
Could SOMEone speak to ezsql lineage...

### ISSUE THREAD

**Issue by CNSKnight** [ezSQL/ezsql#211]
I too have used (something called) EzSQL since forever...
Could SOMEone speak to lineage - IF ANY - IN THE DOCs - to the library w/the SAME name - that I have used since early 2000's
I could find no version in my installed, but scripts include
>  * Copyright (c) 2010 Nabeel Shahzad.
...Anybody?...

**Comment by techno-express** [comment]
What problem you having?

What's the file name you quoting?

Read contribution to page for lineage.
