### ISSUE TITLE
Deprecated: define(): Declaration of case-insensitive constants is deprecated in xxx\ezsql-3\shared\ezFunctions.php on line 189

### ISSUE THREAD

**Issue by moscorp** [ezSQL/ezsql#214]
I am using
php7.4
mysql 5.7

how to solve this error?!

**Comment by moscorp** [comment]
done, just delete the true at the line (I dun know am I right...)

**Comment by moscorp** [comment]
well, I'm facing another problem.
insert into db values (NULL,'10014','123',NULL)

will got the following notice, how can I solve it?

Notice: Trying to access array offset on value of type null in xxx\ezsql-3\shared\ez_sql_core.php on line 245

**Comment by techno-express** [comment]
ezsql at v5, version 3 you are using, PHP 7.4 was not released at that time. 

You can submit a PR on that branch if you want, with updated tests.
