### ISSUE TITLE
lastval throws an error in postgres

### ISSUE THREAD

**Issue by dspindler** [ezSQL/ezsql#217]
I noticed with the latest version that in ez_phsql.php it will try and get the insert_id by selecting the lastval(). However if the table doesn't have a series then selecting lastval instead reports an error. Once you've inserted into a table with a series you won't receive that error anymore as lastval will return that value. 
 PHP Warning:  pg_query(): Query failed: ERROR:  lastval is not yet defined in this session in /var/www/html/dataentry/vendor/ezsql/ezsql/lib/Database/ez_pgsql.php on line XXX

psql (PostgreSQL) 10.21
PHP 7.4.19

Example:
 create table test (myid int not null);
 insert into test values (2);
select lastval();
ERROR:  lastval is not yet defined in this session

**Comment by TheTechsTech** [comment]
Not enough info provided, will need a full **_proper_** code sample/example. 
What **_ezsql_** version you using? And what is line `XXX`? 
>PHP Warning: pg_query(): Query failed: ERROR: lastval is not yet defined in this session in /var/www/html/dataentry/vendor/ezsql/ezsql/lib/Database/ez_pgsql.php on line XXX

Maybe add PR with that as an test to: https://github.com/ezSQL/ezsql/blob/cccbe8a1318e13a0003307629fdb8535d0a4e05a/tests/postgresql/postgresqlTest.php#L3

**Comment by TheTechsTech** [comment]
Reopen with additional info that's needed.
