### ISSUE TITLE
SHOW CHARACTER SET and SET NAMES ''

### ISSUE THREAD

**Issue by carlo-fontanos** [ezSQL/ezsql#220]
**Describe the bug**
Every time I run a SELECT query, I notice on that the following queries also get executed: 
```
SHOW CHARACTER SET 
SET NAMES ''
```
- Is this normal behavrior? 
- How to stop these queries from executing?

**To Reproduce**
Try running a SELECT statement. 

**Environment:**
 - EZSQL Version : V4
 - PHP Version: 7.4
 - SQL Driver: mysql

**Comment by carlo-fontanos** [comment]
Hello, thanks for the quick reply. 

Here is the full SQL query statement example with PHP: 
```
<?php 
require 'vendor/autoload.php';

use ezsql\Database;

define( 'DB_NAME', 			'mydb' );
define( 'DB_USER', 			'root' );
define( 'DB_PASSWORD', 		'password');
define( 'DB_HOST', 			'127.0.0.1' );

$db = Database::initialize('mysqli', [DB_USER, DB_PASSWORD, DB_NAME, DB_HOST], 'db1');

$result = $db->get_var("SELECT COUNT(cid) FROM customer");

print_r($result);
```

And here's the result when I use `SET GLOBAL general_log = 'ON';` (this is where I'm getting the exeuction info from)
```
2023-01-04T03:47:30.513881Z	 1669 Connect	root@localhost on mydb using TCP/IP
2023-01-04T03:47:30.514375Z	 1669 Query	SET NAMES utf8
2023-01-04T03:47:30.514583Z	 1669 Init DB	mydb
2023-01-04T03:47:30.514750Z	 1669 Query	SHOW CHARACTER SET
2023-01-04T03:47:30.516131Z	 1669 Query	SET NAMES 'utf8'
2023-01-04T03:47:30.516353Z	 1669 Query	SELECT COUNT(cid) FROM customer
2023-01-04T03:47:30.531272Z	 1669 Quit
```

Notice the `SET NAMES utf8` and `SHOW CHARACTER SET` - everytime I run a SELECT I see these 2 queries. And on our production site they're the most executed query recorded.

**Comment by TheTechsTech** [comment]
I think you will need to understand how PHP `mysqli_query` function or how the internals MySQL driver works. 

Check `lib/Database/ez_mysqli.php` at query(), connect() and dbSelect() methods, and overwrite them.

**Comment by carlo-fontanos** [comment]
I've been trying to understand the code under lib/Database/ez_mysqli.php but I'm still not sure if it's safe to comment out / remove this code: 

```
if ($charset != '') {
    $encoding = \strtolower(\str_replace('-', '', $charset));
    $charsetArray = array();
    $recordSet = \mysqli_query($this->dbh, 'SHOW CHARACTER SET');
    while ($row = \mysqli_fetch_array($recordSet, \MYSQLI_ASSOC)) {
        $charsetArray[] = $row['Charset'];
    }

    if (\in_array($charset, $charsetArray)) {
        \mysqli_query($this->dbh, 'SET NAMES \'' . $encoding . '\'');
    }
}
```
From my tests on the application, everything still seems to be functioning properly.

Please advice.
