### ISSUE TITLE
Postgres: INSERT queries into tables that do not have an autoincrement column do not work

### ISSUE THREAD

**Issue by alex94040** [ezSQL/ezSQL#61]
Scenario: 
An association table called "userinventory" that has two columns, both are foreign keys: userId and ingredientId. There is no autoincrement column. 

Query: INSERT INTO userinventory (userid, ingredientid) VALUES (179, 3), (179, 5);

This query does not work in ezSql because ezSql attempts to get the insertID - and there is not one. The error message is:

Warning: pg_query(): Query failed: ERROR: lastval is not yet defined in this session in ..../ez_sql/postgresql/ez_sql_postgresql.php on line 220

Warning: pg_fetch_row() expects parameter 1 to be resource, boolean given in ..../ez_sql/postgresql/ez_sql_postgresql.php on line 221

**Comment by gnowxilef** [comment]
+1
