### ISSUE TITLE
After 500 queries script reconnects after each query

### ISSUE THREAD

**Issue by yohancreemers** [ezSQL/ezSQL#72]
The test `$this->num_queries >= 500` on line 207 of mysqli/ez_sql_mysqli.php will be `true` for each query as soon as the the 500 limit has been passed.

Suggestion: the test `$this->num_queries % 500 == 499` will be `true` each 500st query.

**Comment by ozh** [comment]
On a mobile right now but I guess the same snippet should go in all the ez_sql_* components (mysql, mysqli, pdo, ...)
