### ISSUE TITLE
Work wtih UoW (unit of work) and Transctional! How to?

### ISSUE THREAD

**Issue by francescobianco** [ezSQL/ezSQL#80]
[EDITED] What is the right way to use UoW (unit of work) with EzSQL?

The transactions are useful features of modern DBO, please show how to implement that

Actually this question is opened on Laravel
https://github.com/laravel/ideas/issues/495

**Comment by techno-express** [comment]
I will review, and see how too proceed.

**Comment by techno-express** [comment]
It seems it's a feature I don't use in any of my projects. I will need to see an use case, an problem that using the feature will help. 

I see things in the way the developer is designing, structuring the app to access the database.

modern DBO are bloated!

**Comment by techno-express** [comment]
Refactoring will be routines dedicated to, however it depends on use case and how one is designing there application. I still have no use case, but will be in an v4 branch release.
