### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by francescobianco** [ezSQL/ezSQL#81]
According to the PRW http://www.phptherightway.com/ and other PSR the source code in not compliant ! Planning a refactoring??

I'm ready to contribute!! 

Star+1

**Comment by gnowxilef** [comment]
PR always welcome. :)

**Comment by techno-express** [comment]
will do.

**Comment by techno-express** [comment]
your project is similar to what's here. your project has an create schema routine that will eventually be implemented here. a lot has been improved in current release, so if you see what needs refactoring submit PR.

**Comment by techno-express** [comment]
refactoring will be in an v4 branch release, and be psr-2, psr-4, and psr-11 compliance.
