### ISSUE TITLE
ezSQL abnormal behaviour

### ISSUE THREAD

**Issue by bhumiradixweb** [ezSQL/ezSQL#82]
I am using ezSQL for database queries and connection and sometimes it gives data and sometimes it return no results.

Here is the debug code

```
Query [3] -- [SELECT * FROM table WHERE `id`=4]
Query Result..

No Results
```

Database table have records and it return records if i run file after few minutes.

**Comment by jv2222** [comment]
You probably need to talk to your hosting provider as it sounds like the
infrastructure you are using is flakey. Or there is a flakey  network
connection. Or mysql keeps dying on connect for some reason.

For example a database connection that sometimes works and sometimes
doesn't. Or perhaps a load balancer that is polling multiple machines with
multiple databases and some of the machines do not have data on them.

To be honest there are many possibilities for this type of behavior but I
think ezSQL itself is very unlikely.

**Comment by bhumiradixweb** [comment]
Okay Thanks. Will check oncde with hosting provider.
