### ISSUE TITLE
escape() function

### ISSUE THREAD

**Issue by portal64** [ezSQL/ezSQL#83]
Hi, I'm new in github and I'm not sure if I can ask this question here..

It's about the $db->escape() function; Where should I use it?  Always that I get data from a user form (via GET or POST) ???

It's really secure to use this function to avoid all Sql Injection attempts ?

Thanks!
Raúl.

**Comment by gnowxilef** [comment]
yes, you can use it for any input, including user form. you can get more info from the [docs](https://ezsql.github.io/ezSQL/ez_sql_help.htm).
