### ISSUE TITLE
How to write row count on secreen?

### ISSUE THREAD

**Issue by mrcherie** [ezSQL/ezSQL#86]
Hello,
I'm using ezSql and i have a mysql database.
I want to print on screen row count.
How can i do it.

Thanks

**Comment by gnowxilef** [comment]
once you execute your query, you can use `$db->num_rows` to get the number of rows.

**Comment by gnowxilef** [comment]
you can look at the section "ezSQL variables" in the [docs](https://ezsql.github.io/ezSQL/ez_sql_help.htm).

**Comment by mrcherie** [comment]
thanks
