### ISSUE TITLE
sqlsrv insert_id returns nothing

### ISSUE THREAD

**Issue by muratyavuz** [ezSQL/ezSQL#93]
Hi, after inserting new row to MsSQL database, $db->insert_id returns nothing.

```
if ( preg_match("/^(insert|replace)\s+/i",$query) )
{
    $identityresultset = @sqlsrv_query($this->dbh, "select SCOPE_IDENTITY() AS id");

    if ($identityresultset != false )
    {
        $identityrow = @sqlsrv_fetch($identityresultset);

        $this->insert_id = $identityrow[0];
    }
}
```

$identityresultset returns resource, $identityrow returns bool(true)

**Comment by jv2222** [comment]
Any idea how to fix? If you can solve it please update the code and submit a pull request. Thanks!
