### ISSUE TITLE
Deprecated php functions on php 7.0

### ISSUE THREAD

**Issue by rauldobrota** [ezSQL/ezSQL#94]
Deprecated: Function eregi_replace() is deprecated in ez_sql_mssql.class.php on line 356
Deprecated: Function eregi() is deprecated in ez_sql_mssql.class.php on line 364

The class should be re-written for php 7.0 full compatibility

**Comment by zag2me** [comment]
Hoping for this also

**Comment by Scott-Mc** [comment]
The mssql driver was also removed in PHP 7 so can't just be rewritten.   This legacy driver should be depreciated in favour of either sqlsrv or PDO.
