### ISSUE TITLE
grant queries are failing silently

### ISSUE THREAD

**Issue by omry** [ezSQL/ezSQL#97]
I just spent several hours debugging this.
turns out there is logic in ezsql that detects if a query is a select (in all drivers), and in that case it fetches the rows.
preg_match("/^(insert|delete|update|start|replace|truncate|drop|create|alter|begin|commit|rollback|set|lock|unlock|call)/i",$query) )

if the query is unrecognized (like grant queries) it will assume it's a select and will try to read the resulting data.
since ezsql really likes to hide the errors with @ for every operation, this results in php exiting silently.

the solution is as simple as adding grant to the regexp above, but I think the logic should be reversed:
if something is a select, fetch the data (IE: it has select in the query start).

**Comment by jjarolim** [comment]
Bump. ezSQL tries to detect the kind of query executed but doesn't recognizes GRANT queries.
As a result, GRANT queries get treated as SELECT queries thus triing to fetch rows from a boolean result.

**Comment by jjarolim** [comment]
Bump. Same for FLUSH. Please reverse logic as proposed by omry: detect SELECT statements and treat all other query results as boolean.

You maybe could also examine the result if its boolean or row instances ...

**Comment by omry** [comment]
no a side note, my comment is not from 2016.
if I had to guess, it's sometime from 2008. don't expect help.

**Comment by jjarolim** [comment]
thanks for the response! 
so ezSQL seems to be dead?

What a pitty since i like it very much for small projects ... and of course in the context of WordPress.

Best regards from Salzburg!

**Comment by omry** [comment]
it seems to be in lazy-maintenance mode.
recent commit history seems mostly about small fixes.

https://github.com/ezSQL/ezSQL/commits/master

**Comment by yohancreemers** [comment]
This issue can be solved by replacing the `preg_match` test on line 277 by
`if ( !is_object($this->result) )`

**Comment by jv2222** [comment]
Why not create a pull request? Then felix can merge it for you....
