### ISSUE TITLE
PHP 7.0: Deprecated:  Methods with the same name as their class will not be constructors

### ISSUE THREAD

**Issue by wninaus** [ezSQL/ezSQL#98]
When testing ezSQL on PHP7 I noticed following warning: 
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; ezSQLcore has a deprecated constructor in shared/ez_sql_core.php

**Comment by mvander** [comment]
Yes. I am seeing the same. I would love to start moving to PHP 7 with ezSQL
